### ISSUE TITLE
Add ability to save settings at the VC level

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#101]
This allows the arbitrary setting of a key to a value at the VC level.  This will help to allow the storage of different 'widgets' within the ui.

Note if the settiing key does not exist, return an empty string.

**Comment by craig8** [comment]
Example code for console.
{
    "method": "platforms.uuid.6c448da6-92e7-448f-a8da-8af529002e6e.set_setting",
    "params": {"key": "stuff", "value":"Good"},
    "authorization": "8e6198dd-c3d2-4cc4-bd06-2b3a245f1315"
}

{
    "method": "platforms.uuid.6c448da6-92e7-448f-a8da-8af529002e6e.set_setting",
    "params": {"key": "stuff", "value":"Good"},
    "authorization": "8e6198dd-c3d2-4cc4-bd06-2b3a245f1315"
}

**Comment by craig8** [comment]
Settings should be stored in $VOLTTRON_HOME/data/platform.agent.settings file.  Which they aren't currently.

**Comment by jhaack** [comment]
Charts can be stored
