### ISSUE TITLE
Auth gets in the way when running from command line

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#1022]
Starting an agent through eclipse or pycharm or from the command line is problematic because each individual agent has to be in the auth.json file.  I recommend we update pycharm-launch.py and pydev-launch.py to automatically add those agents that aren't using the default platform keystore to make sure their runtime agents are added to the auth.json file.

Of course adding /.*/ credential in the auth.json file is a way of bypassing this, however NOT to be used in production!

**Comment by jhaack** [comment]
Sounds like a good solution that gets the result without completely violating security
