### ISSUE TITLE
MasterDriverAgent not using the values of campus/building/unit, only the key names.

### ISSUE THREAD

**Issue by ocschwar** [VOLTTRON/volttron#1041]
I have a master driver agent set to scrape a ModbusTCP slave. The modbus config file is as follows: 

`{
    "driver_config": {"device_address": "127.0.0.1", "port":5020},
    "campus": "Shirley-MA",
    "building": "North",
    "unit": "PMC",
    "driver_type": "modbus",
    "registry_config":"/home/volttron/Docs/design-docs/voltron master modbus agent registers.csv",
    "interval": 5,
    "timezone": "UTC",
    "heart_beat_point": "ESMMode"
}
`

Yet the topics by which the driver posts things are just "campus/building/modbus1/SolMetering_L1_to_L2_AC_Voltage" 

I changed volttron/services/core/MasterDriverAgent/master_driver/driver.py as follows to try to fix it, but to no avail:

`        self.base_topic = DEVICES_VALUE(campus=config.get('campus',''),
                                        building=config.get('building',''),
                                        unit=config.get('unit',''),
                                        path=self.device_path,
                                        point=None)
        
        self.device_name = DEVICES_PATH(campus=config.get('campus',''),
                                        building=config.get('building',''),
                                        unit=config.get('unit',''),
                                        base='',
                                        node='',
`

**Comment by craig8** [comment]
this is not using the config store...from what I can tell.  What branch are you using?

**Comment by ocschwar** [comment]
The develop branch.

**Comment by ocschwar** [comment]
I mistakenly thought that removing a wheel and re-installing it would nuke the configuration store.

**Comment by ocschwar** [comment]
Converting to the configuration store fixed the issue. Thanks!

**Comment by craig8** [comment]
Great!
