### ISSUE TITLE
Should not be able to stop essential agents like PlatformAgent

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#107]
If you stop PlatformAgent through VolttronCentral you lose the ability to control that platform and will need to ssh into the box to restart.

Maybe we need a priority scheme:
Agent can be started/stopped at will
Agent can be stopped with a warning dialog
Agent cannot be stopped through UI, only restarted

**Comment by fstshrk** [comment]
We can also force at least one instance of platform agent to be running at all times.

Although this could make upgrading that agent a bit tougher.
