### ISSUE TITLE
VC Web interface crashes when platform agent has communications error.

### ISSUE THREAD

**Issue by acedrew** [VOLTTRON/volttron#1098]
When a platform has an issue with communications for its platform.agent, the web ui crashes completely and must be killed in Chrome 54.0.2840.99 on Windows 

More specifically, if you click the arrow to expand the list of agents on that platform in the left sidebar, a jsonrpc call is made with no response, leading to the UI hanging and eventually crashing.

This could be as general as any jsonrpc call timing out causes the interface to crash. With the console open, the last message that is displayed before becoming unresponsive is "Wating for response...."

**Comment by craig8** [comment]
@acedrew this should be fixed in the developer and releases/4.0.1 branches #961 is a reference for how this was addressed and though not specifically what you are mentioning it has been fixed in those branches non the less :)
