### ISSUE TITLE
DOC: License in repo root directory?

### ISSUE THREAD

**Issue by nehalecky** [VOLTTRON/volttron#11]
Hey volttron team! This looks like a great project. I was interested to understand better the licensing? I see various FreeBSD licences throughout the repo, however, believe these are associated with specific implementations of agents? Please let me know if I am overlooking something. Thank you.

**Comment by craig8** [comment]
I am going to close this now @nehalecky  you should check out the first release of 3.0 beta 45f2021354e4fa7ebb9b9ffb6bb1048c6a6b5516
