### ISSUE TITLE
browser memory leak with charts

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#1112]
After having charts running for a while I end up with 
![image](https://cloud.githubusercontent.com/assets/3979063/21625505/d4dfff58-d1c0-11e6-800c-bdd93dc466a8.png)

I will  leave the developer window open to see what if anything is shown there. 

After refreshing and looking at dev tools the following shows up

![image](https://cloud.githubusercontent.com/assets/3979063/21625624/5d11fd18-d1c1-11e6-860f-b58f96376669.png)

**Comment by craig8** [comment]
The picture with the Websockets was a configuration issue with our external vc host.  

However with the latest develop and releases/4.0.1 code I have the following 

![image](https://cloud.githubusercontent.com/assets/3979063/21631885/409e9676-d1f5-11e6-9817-05fbc25d0519.png)

**Comment by jchap-pnnl** [comment]
Commits 27f0be2, 60024b0, and a347d05 pertained to this issue.

**Comment by craig8** [comment]
Merged new chart lib in #1229
