### ISSUE TITLE
Accelerated simulations using the VoltTron master driver agent. 

### ISSUE THREAD

**Issue by ocschwar** [VOLTTRON/volttron#1131]
Hi, all. Right now I am running simple tests with VoltTron using a Modus-TCP server. Every time the MDA scrapes it, the server updates its registers based on its set points and the devices they are meant to represent. 

During the 5 second interval between scrapes, VoltTron uses under 500ms of CPU time, so there's plenty of opportunity to accelerate these runs. 

I figure the way to do it is to have a MetronomeAgent that posts timestamps representing the simulated passage of time. each time it posts, the MasterDriver agent can run its run. Then each agent that relies on that scrape, after processing its contents, can post a message to the metronome agent. After the metronome has been poked by each agent known to it (through the configuration), it pokes the master driver agent, and the cycle begins anew. 

Has anyone done anything along these lines yet?

**Comment by jhaack** [comment]
NREL has done something similar with a system they call VOLTTIME. Send us an email and I will connect you with them.
