### ISSUE TITLE
Long running BACnet scrapes timeout in the master driver.

### ISSUE THREAD

**Issue by acedrew** [VOLTTRON/volttron#1136]
When scraping a large number of points from a slower/older BACnet device, the BACnet proxy can still be scraping when the hardcoded timeout from the master driver expires. This is set to 10 seconds and is not changeable by config. 

This problem was experienced scraping ~1400 points from a JACE that would only support 30 points per request. It is not dependent on scrape interval.

**Comment by acedrew** [comment]
Submitted #1134 to resolve

**Comment by craig8** [comment]
@acedrew Are we all good with this now that your fix has been merged?

**Comment by acedrew** [comment]
I think so, certainly with the scope of this issue.
