### ISSUE TITLE
Where is version 4.0 document?

### ISSUE THREAD

**Issue by so3500** [VOLTTRON/volttron#1142]
I am studying version 4.0 of Voltron. But the document is only 3.x. Name of agent (ex. PlatformAgent -> VolttronCentralPlatform). Where can I get the 4.0 version of the Voltron document?

**Comment by craig8** [comment]
http://volttron.readthedocs.io/en/4.0.1/ all of the current documentation is up on the readthedocs site.  You can get any of the versions from there.  There is a link on the bottom left of the page that has the version of the document going with the release.

The next release will be 4.1 after a mini release of 4.0.1 which will be transitioned to master within the next week.

**Comment by so3500** [comment]
Thank you for your reply.
![1](https://cloud.githubusercontent.com/assets/19392136/21917857/722acc96-d98e-11e6-8bab-06e34fdf1c8b.PNG)

However, when i click Downloads / PDF, the Release 3.5RC1 document appears.
Should I then only rely on the site?

**Comment by craig8** [comment]
Once you go to one of the other versions I believe the PDF will be what you want.  Note the PDF is just a rendering of what is online

**Comment by so3500** [comment]
Thank you very much for your quick reply.
