### ISSUE TITLE
Need to add an auth entry for agents running outside the platform

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#1172]
volttron-ctl auth add
domain []: 
address []: 
user_id []: 
capabilities (delimit multiple entries with comma) []: 
roles (delimit multiple entries with comma) []: 
groups (delimit multiple entries with comma) []: 
mechanism [CURVE]: 
credentials []: /.*/
comments []: 
enabled [True]: 
added entry domain=None, address=None, mechanism='CURVE', credentials=u'/.*/', user_id='ff6fea8e-53bd-4506-8237-fbb718aca70d'

**Comment by craig8** [comment]
This is not what should happen...it shouldn't make things unsafe when running in eclipse.  It should add a specific agent if an ENV var is set... Thats my thinkin anyways.
