### ISSUE TITLE
Anon improvement

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#1184]
Anonymization data in a historian will require a VolttronCentralPlatform agent to be installed on the instance.

The historian will have a flag for determining whether anonymization should be enabled or not, by default this setting will be False (not anonymizing)

Only the anonymized topics will be written to the database (the others will be cached and an error will be alerted as an error)

**Comment by schandrika** [comment]
Is something more than topic replacement string required to achieve the same purpose ?

**Comment by jhaack** [comment]
I think this was a check to ensure only anonymized data was written to the DB. Use case is no longer a priority unless someone in the community raises it.

**Comment by schandrika** [comment]
No longer a priority. Can be reopened if community has a need for this
