### ISSUE TITLE
BACnet Proxy agent fails to retrieve points list from devices that the BACpypes script works on.

### ISSUE THREAD

**Issue by acedrew** [VOLTTRON/volttron#1188]
proxy_grab_bacnet_device_config.py fails where grab_bacnet_device_config.py works, reports segmentation error regardless of whether the device in question supports segmentation or not.

See error here: https://gist.github.com/acedrew/9cb9f05778e701afbcb5269abd71db3b

**Comment by craig8** [comment]
@acedrew please verify with newest develop.  Thanks

**Comment by acedrew** [comment]
This seems to be resolved in latest develop, tested today, however issue #1206 became apparent.

**Comment by acedrew** [comment]
Please close as resolved and reference the commit

**Comment by craig8** [comment]
https://github.com/VOLTTRON/volttron/pull/1201/commits/2da55ee57dfa41b74861568e0cb2b0fc42f7656a
