### ISSUE TITLE
New VIP subsystem to improve sending to multiple recipients

### ISSUE THREAD

**Issue by hashstat** [VOLTTRON/volttron#119]
Currently, if an agent must send a message to N recipients, it must iterate over the recipient list and send the message N times updating the recipient with each send. Consider creating a new router subsystem which takes a list of recipients along with a message and sends the message to each recipient on behalf of the sender. This would help reduce the backlog of messages the router needs to handle and the number of messages a peer must send. It would be particularly beneficial to the pub/sub subsystem.

**Comment by hashstat** [comment]
Consider adding a new subsystem named 'manycast' or 'multicast' which expects a list of recipients, followed by an empty frame to mark the end of the list, followed by a subsystem and its associated frames.

Here is an example VIP message received by the router from the pubsub service requesting that the router distribute a pub/sub message on behalf of dan to the agents with identities alice, bob, and chuck:

sender | recipient | proto | user-id | msg-id | subsystem | peer1 | peer2 | peer3 | delim | subsystem | data
------ | --------- | ----- | ------- | ------ | --------- | ----- | ----- | ----- | ----- | --------- | ----
"pubsub" | "" | "VIP1" | "" | "" | "manycast" | "alice" | "bob" | "chuck" | "" | "rpc" | '{"jsonrpc"="2.0", "method"="pubsub.push", "params"=["dan", "", "some/topic", {}, "hello"]}'

The router would then turn this into the following outgoing messages:

recipient | sender | proto | user-id | msg-id | subsystem | data
--------- | ------ | ----- | ------- | ------ | --------- | ----
"alice" | "pubsub" | "VIP1" | "" | "" | "rpc" | '{"jsonrpc"="2.0", "method"="pubsub.push", "params"=["dan", "", "some/topic", {}, "hello"]}'
"bob" | "pubsub" | "VIP1" | "" | "" | "rpc" | '{"jsonrpc"="2.0", "method"="pubsub.push", "params"=["dan", "", "some/topic", {}, "hello"]}'
"chuck" | "pubsub" | "VIP1" | "" | "" | "rpc" | '{"jsonrpc"="2.0", "method"="pubsub.push", "params"=["dan", "", "some/topic", {}, "hello"]}'

Please note that these are notification messages and do not require a reply. The user-id is empty because the pubsub service communicates over an inproc: socket and is, therefore, part of the router process.

**Comment by craig8** [comment]
With the modifications that @shwethanidd  is working on I think this will get taken care of in a different manner, but this is going to be addressed. @shwethanidd  please look this over and lets talk about it.

**Comment by shwethanidd** [comment]
Since the platform pubsub is going to be part of router, the router will have list of subscriptions and it will send the message to all subscribers on the behalf of the publisher. 

However, if the message needs to be sent to only a subset of subscribers, then this feature will need to be added. List of peers needs to be part of the message similar to what is described above. The peer list needs to be part of the message similar to what is described above. Router will then only send to this peer list.

**Comment by jhaack** [comment]
Completed
