### ISSUE TITLE
The difference between origin/releases/4.0.1 and releases/4.0.1

### ISSUE THREAD

**Issue by so3500** [VOLTTRON/volttron#1195]
I am currently running volttron with version 4.0.1 of volttron. Is there a difference between the two branches in git?
![112](https://cloud.githubusercontent.com/assets/19392136/23050312/d7a7648a-f504-11e6-89ea-8198183f7d22.PNG)

**Comment by craig8** [comment]
Seems like local versus remote...Since you closed this I bet hats what you found out.
