### ISSUE TITLE
smap issues

### ISSUE THREAD

**Issue by moshanrel** [VOLTTRON/volttron#12]
Hi Volttron Team,

I am a developer at NREL. I am trying to use volttron and set up a smap server locally. However, I found the smap installation guideline at http://www.cs.berkeley.edu/~stevedh/smap2/install.html is outdated. Those easy installation methods such as ppa as well as some listed Debian packages (e.g., Berkeley v4.8 Database Libraries for readingdb) don't work with current Ubuntu (14.04.1) . It seems manual installation from the sources is the only option. Moreover, the "execute_manager" used in powerdb2 deprecated in Django 1.4 as part of the project layout refactor and was removed in 1.6. I am currently using python 2.7.6 and django 1.6.1. Do you use an old version of Django to accommodate powerdb2  or you have updated some powerdb2 source files? 

In your next released version 2.0, will you provide an user guide with more details about smap installation?

BTW, do you have a public accessible smap server for volttron test runs? 

I would greatly appreciate if you could shed some lights on these questions.

Mo Sha

**Comment by craig8** [comment]
Is there any other information about 14.04 Ubuntu examples?

**Comment by fstshrk** [comment]
Hi Craig

I can give it another try and tell you what goes wrong. I believe the issue
was incompatibility with smap front end and django.
