### ISSUE TITLE
Expansion of device config fails on firefox

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#1221]
After the initial iam responses, expanding to fetch the points on a device the table does not show up in firefox.

This has been tested on both vm and windows versions to the same effect

Note right below this space on the vc ui is another entry.

![image](https://cloud.githubusercontent.com/assets/3979063/23495320/e777c694-fecc-11e6-8453-0df8927687b6.png)

**Comment by craig8** [comment]
This was not an error the devices didn't return any points that had a presentValue property.

**Comment by acedrew** [comment]
Should this be left open until an appropriate error message is added?
