### ISSUE TITLE
proxy_grab_bacnet_config.py ValueError not handled

### ISSUE THREAD

**Issue by acedrew** [VOLTTRON/volttron#1284]
A format string passed the wrong type raises a ValueError, only TypeErrors were being handled, causing the script to fail for devices that did not fit the ":.6g" format string.

**Comment by schandrika** [comment]
PR #1285 fixes only formatting. @jklarson  could you test this and update exception handling if needed

**Comment by bonicim** [comment]
@kefeimo Can you please verify that this issue was fixed by #1285?

**Comment by craig8** [comment]
These are handled now.  
https://github.com/VOLTTRON/volttron/blob/127dff67a43748b378ff6dfa03672dfc18ba48d8/scripts/bacnet/grab_bacnet_config.py#L216
