### ISSUE TITLE
SQLHistorian ignores query end timestamp if start parameter is used

### ISSUE THREAD

**Issue by schandrika** [VOLTTRON/volttron#1304]
Happens only in SQLHistorian and not in MongodbHistorian

**Comment by hlngo** [comment]
I found the issue in SQLite. So you may want to test for other SQL* DBMS.

**Comment by schandrika** [comment]
Fixed issue sqlite, mysql, and crate historians. Will create pull request shortly

**Comment by hlngo** [comment]
Have you created a PR for this?

**Comment by craig8** [comment]
There has not been a PR for this yet @hlngo

**Comment by schandrika** [comment]
Fixed with PR #1267
