### ISSUE TITLE
VOLTTRON debugging improvement and additional features

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#131]
Let's use this space to discuss what features we would like in a VOLTTRON debugging tool

**Comment by hashstat** [comment]
Here is a quick list of features I would like to see:
* Remote debugging
  - Dynamically attach to a running agent
  - Gain an interactive Python interpreter prompt
* Dynamically change logging levels
* Attach directly to running agent's log stream
* Inspect VIP stream of individual agents

**Comment by jhaack** [comment]
Covered in other issues
