### ISSUE TITLE
Investigate modbus_tk to swap out pymodbus

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#1366]
modbus_tk is not tied to the Twisted library.  This is one of the reasons for not going with 3x versions of python.

From @ffreckle:  We have been using this for a few years for both TCP and RTU modbus.  The biggest issue will be gevent support but I’ve made contributions to modbus_tk and will give the maintainer a heads up on that.

**Comment by schandrika** [comment]
volttron core now supports both pymodbus and modbus-tk

**Comment by jklarson** [comment]
A Modbus-TK driver exists [in the core VOLTTRON repository](https://github.com/VOLTTRON/volttron/tree/develop/services/core/MasterDriverAgent/master_driver/interfaces/modbus_tk):
