### ISSUE TITLE
PostgreSQL SQLHistorian

### ISSUE THREAD

**Issue by tnesztler** [VOLTTRON/volttron#1390]
Since implementation of SQL databases such as MySQL are already in place, the support for a PostgreSQL variant would be appreciated.

As suggested in this [closed issue](https://github.com/VOLTTRON/volttron/issues/68), the module [Psycopg2](http://initd.org/psycopg/docs/module.html) (limited to v2.4.6 with Python 2.x support) which respects the DB API 2.0 specification could be used.

**Comment by sysid** [comment]
I support this request, especially when thinking of upcoming TimescaleDB.
