### ISSUE TITLE
Example agent for storing and querying data in the historian

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#141]
Create an example agent to:
- [x] Publish data to "datalogger" topic
- [x] Query for data and print to console

- [ ] Publish data to "record" topic (json object)
- [ ] Query for object from "record" and print to console

**Comment by craig8** [comment]
See https://github.com/VOLTTRON/volttron/wiki/Historian-Topic-Syntax for syntax requirements.
