### ISSUE TITLE
VOLTTRON should report invalid configuration

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#1448]
VOLTTRON should log the configuration when starting up at info level.  If any property in the config file is invalid it should report at ERROR level and then stop the platform.

**Comment by acedrew** [comment]
This is the same issue as #1322

**Comment by mikeroup** [comment]
I have logging handled but we can't really take care of the regular config file since it gets read in parse_args, before logging is set up.

**Comment by craig8** [comment]
Print to standard error if there is an incorrect value in the config file i.e. an unknown key 

If someone puts in

vpi-address = tcp://blah:22916

Then the platform should not blissfully start

**Comment by craig8** [comment]
@acedrew slightly different but definitely related as the configuration versus the logging config is two different files...but @mikeroup  is going to make everything good with this anyways!

**Comment by craig8** [comment]
@acedrew how do you determine if the logging file is invalid?

**Comment by schandrika** [comment]
Fixed in PR #1472
