### ISSUE TITLE
Spurious error when using config edit to create a new config

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#1484]
RPC error is thrown, but new config entry is created and can then be edited. Error just being thrown on a check and could cause confusion.

```` 
('RPC ERROR', 'Traceback (most recent call last):
File "/home/jer/git/volttron-craig/volttron/platform/vip/agent/subsystems/rpc.py", line 169, in method    
  return method(*args, **kwargs)
File "/home/jer/git/volttron-craig/volttron/platform/store.py", line 256, in manage_get_metadata
  raise KeyError(\'No configuration file "{}" for VIP IDENTIY {}\'.format(config_name, identity))
  KeyError: \'No configuration file "config" for VIP IDENTIY forwarder2\'\n')
`````

**Comment by kmonson** [comment]
This is a result of trying to get the meta data for a file that does not exist. I'm not sure how to fix this other than returning error codes instead of raising an exception.

**Comment by kmonson** [comment]
I guess we could always return None if it doesn't exist.
