### ISSUE TITLE
Master Driver Agent problem 

### ISSUE THREAD

**Issue by geyin96** [VOLTTRON/volttron#1503]
The allowable time for reading data (only 10s) is hard-coded in the master driver interfacing Bacnet (.../master_driveragent-2.0/master_driver/interfaces/bacnet.py), which causes error when large amount data is to be imported. After extending the timeout to 100s the master driver agent is able to publish all the data. If the timeout value could be set as a parameter in the master driver configuration file that would be much better.

**Comment by kmonson** [comment]
What version of VOLTTRON are you using? Are you still on 4.0? In develop and 4.1 there is a timeout setting that can be used to change the  timeout of the rpc called to the bacnet proxy.
