### ISSUE TITLE
How about adding an Apache Kafka agent?

### ISSUE THREAD

**Issue by so3500** [VOLTTRON/volttron#1525]
kafka is a distributed platform capable of handling large volumes of messages.

I think these platforms will be useful for VOLTTRON, which needs to collect and process large amounts of data.

Currently I'm testing the example of agent.

This agent has the following functions.

1. Send subscribed data from MessageBus to apache kafka broker

2. Publish the data received from the kafka broker to MessageBus

The link below is the official site of apache kafka.
https://kafka.apache.org/

How about adding an Apache Kafka agent?

**Comment by so3500** [comment]
Apache Kafka supports the JAVA API. However, I implemented one using one of the famous libraries that support Python.
https://github.com/dpkp/kafka-python

**Comment by craig8** [comment]
Sounds like you have the experience to build that agent.  It would really cool to integrate with more open source projects!

**Comment by so3500** [comment]
Thank you very much for showing positive response.

I'll send a pull request after an additional simple test and source code modification.

Could you please give me the necessary precautions for a pull request?

Thank you.

**Comment by jhaack** [comment]
Are you on the VOLTTRON office hours? I think this would be a good contribution to highlight next meeting.

**Comment by so3500** [comment]
Are you referring to this link?
https://volttron.org/office-hours

Sadly, there is something I have to deal with at the time.

**Comment by craig8** [comment]
http://volttron.readthedocs.io/en/releases-4.1/community_resources/contributing.html#contributing is our contributing documentation...

Make sure you are working against the develop branch.  In general your code should go into a contrib folder such as https://github.com/VOLTTRON/volttron/tree/develop/services/contrib.  There are two user contributed agents in there already.  

There is a "general" agent builder that can be accessed via volttron-pkg init.  From that you will see the newest method for creating from an agent template.

**Comment by so3500** [comment]
Thank you for the detailed instructions.
I'll update the description and code for the kafka Agent by referring to the contributing documentation.

**Comment by so3500** [comment]
I am currently testing an Kafka agent and have an unknown error.
Below is a picture of Kafka agent.
![screenshot from 2017-11-07 12-44-20](https://user-images.githubusercontent.com/19392136/32476519-3219f54c-c3bb-11e7-8307-420575a896ab.png)

And the picture below is the big picture that I think (Kafka agent will be the picture like below if you think the data collected from Voltron is collected from the cloud or center!
![screenshot from 2017-11-07 12-44-35](https://user-images.githubusercontent.com/19392136/32476526-3a96b25a-c3bb-11e7-8ef8-b1bc91230652.png)

Anyway, the function is good. I have confirmed that both of the above functions work well. 

1. Send subscribed data from MessageBus to apache kafka broker and then, comsumer is received from broker
![kafka_4](https://user-images.githubusercontent.com/19392136/32476588-9c9e0f5c-c3bb-11e7-9250-75940a564ab4.png)

2. Publish the data received from the kafka broker to MessageBus and then, check with the listener agent.
![kafka_3](https://user-images.githubusercontent.com/19392136/32476608-bbb0022e-c3bb-11e7-968e-b23435beaa3a.png)


But, There is a json error log in the log file. When I contacted kafka-python, have a look at the logging system of the Voltron internal system. 
https://github.com/dpkp/kafka-python/issues/1228

![kafka_2](https://user-images.githubusercontent.com/19392136/32476646-ef613fde-c3bb-11e7-97f2-54651d5eb8ea.png)
![kafka_error_2](https://user-images.githubusercontent.com/19392136/32476647-f1df429c-c3bb-11e7-9473-1f69dd820ecd.png)


Could you help me? Do I need to pull the code once?

**Comment by so3500** [comment]
Thank you for your reply.

Well, there is one more issue. 

Currently, the consumer of KafkAgent checks for the existence of a message before fetching it from the broker. However, I used the periodic annotation provided by VOLTTRON to perform this logic (whereas in VOLTTRON, each agent seems to perform the asynchronous method through the callback function when communicating with the message bus) The most ideal way seems to be using asynchronous communication.

According to my research, the asynchronous libraries available in the python2 version are [gevent](http://www.gevent.org/) , [Tornado](http://www.tornadoweb.org/en/stable/).

Is there a good idea to allow VOLTTRON to communicate asynchronously with external systems ??

**Comment by kmonson** [comment]
VOLTTRON is built on top of gevent so you are free to use that in your code. You could start a greenlet that runs a processing loop that blocks until something comes in from the broker. That is basically what we do with ZMQ right now for the message bus.

**Comment by sonjinho** [comment]
Ummm The error should be check this url  (https://github.com/VOLTTRON/volttron/blob/master/volttron/platform/agent/utils.py#L372)

In my Opinion VOLTTRON logging Format Setting is JsonFormat .

**Comment by schandrika** [comment]
Kafka Agent is now part of volttron core. It is under volttron/core/contrib
