### ISSUE TITLE
In some previous versions of develop, DataPuller can kill the router

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#1532]
If DataPuller at commit: e6ff78b56f4b924a4f1d8100bf978a96f33de603,  attempts to connect to VOLTTRON 5.0, it causes the 5.0 router to crash due to going down an unexpected code path.

Short term: catch the key error to eliminate the crash.
Long term: identify the problem and if it is wider than that commit.

**Comment by craig8** [comment]
@shwethanidd and @jhaack where are we on this?

**Comment by shwethanidd** [comment]
It's fixed and ready for merge into develop branch.

**Comment by craig8** [comment]
@jhaack I believe you have tested this...I wish we had a reference to the code though.  You have tested this correct?

**Comment by shwethanidd** [comment]
Fixed in commit # 5bb830513b3b24a148a2e07554bd301c1d35d57c
