### ISSUE TITLE
Issue on the installation of bacnet proxy agent (solution found)

### ISSUE THREAD

**Issue by geyin96** [VOLTTRON/volttron#1544]
When I packed up the bacnet proxy agent in volttron 4.1, the error shows:
![bug_string_nontype](https://user-images.githubusercontent.com/29635351/31948927-07c25304-b8a6-11e7-86a2-f16f6619e560.PNG)

Then I fixed it by modifying the code in async.py as below:
![capture](https://user-images.githubusercontent.com/29635351/31949000-4011e3b4-b8a6-11e7-81d1-ffdc784acab3.PNG)

**Comment by kmonson** [comment]
This happens when the platform Python is compiled in such a way as to remove all docstrings from the standard library. We were aware of the problem and I could _swear_ we had fixed it. We'll get the fix into 5.0 rc branch shortly.

**Comment by craig8** [comment]
@geyin96 you mention you had this issue in volttron 4.1 would you be willing to create a pull request with this fix in it to patch the version you are using...then @kmonson can propagate that to the other versions.
