### ISSUE TITLE
ForwardHistorian unable to connect to remote platform if remote platform not initially up.

### ISSUE THREAD

**Issue by carlatpnl** [VOLTTRON/volttron#1569]
< releases/5.0rc>

NOTE:  to reproduce, you must use 2 separate physical platforms, the problem does
		not exhibit if using loopback addresses, it is unclear if
		the problem exhibits when using a single physical address (non-loopback)
		but different ports.
scenario:		
   assure platform2 is down and not running
   start ForwardHistorian on platform1
   after ForwardHistorian attempts to connect to platform2, start platform2.
   Platform1 never is able to connect to platform2 unless it is shutdown and restarted
   while platform2 is still up.

NOTE: THIS IS A SPECIFIC INSTANCE OF A MORE GENERAL PROBLEM THAT AN AGENT
CAN NOT LOOP TRYING TO CONNECT TO A REMOTE PHYSICAL PLATFORM THAT IS NOT CURRENTLY UP AND BE ABLE TO SUCCESSFULLY CONNECT TO IT ONCE IT COMES UP.  IF THE REMOTE PHYSICAL PLATFORM IS ALREADY UP WHEN CONNECTION IS ATTEMPTED, THERE IS NO PROBLEM, BUT IF THE REMOTE PHYSICAL PLATFORM IS NOT UP AT THE TIME THE FIRST ATTEMPT IS MADE, CONNECTION CAN NOT BE MADE EVEN AFTER THE REMOTE PHYSICAL PLATFORM COMES UP.

**Comment by craig8** [comment]
This is also unable to be reproduced based upon my tests #1570
