### ISSUE TITLE
No data in volttron.log when using log configs other than rotatingLog.py

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#158]
Using the rotatinglog config files results in an empty log file

**Comment by jhaack** [comment]
rotatingLog.py works, the config file does not.

**Comment by jhaack** [comment]
Get rid of other configurations since they do not work anyway.

Make rotatingLog.py default to INFO

**Comment by mikeroup** [comment]
Should the logic to handle other types of configs be removed as well?
