### ISSUE TITLE
self.vip.pubsub.unsubscribe("pubsub", None, None) creates KeyError exception when no subscriptions are present

### ISSUE THREAD

**Issue by 8minutenergy** [VOLTTRON/volttron#1591]
self.vip.pubsub.unsubscribe("pubsub", None, None) when called without any present subscriptions gives a KeyError exception. 

I suggest correct behavior is to return success without an exception in this case.

**Comment by kmonson** [comment]
I agree. I thought we already had an issue for this.

**Comment by craig8** [comment]
#1486
