### ISSUE TITLE
Add point scaling into the driver infrastructure

### ISSUE THREAD

**Issue by 8minutenergy** [VOLTTRON/volttron#1598]
In the modbus and bacnet (and other drivers), allow for automatic scaling of the point value based on the configuration for that point. Allow for different scaling factors for each point.

An addition would be to add unit conversions but that is unnecessary for our use case.

**Comment by ffreckle** [comment]
@8minutenergy Hi Bora, the modbus driver in #1587 does support a transformation on any register.  This can be used for scaling or unpacking proprietary datatypes. For an example, look at the modbus_tk/maps/ion6200.csv or ion8600.csv.

**Comment by acedrew** [comment]
This can be closed.
