### ISSUE TITLE
Volttron Center Dashboard not show in [VOLTTRON 5.0 RC2]

### ISSUE THREAD

**Issue by vishuPPatel** [VOLTTRON/volttron#1602]
setup volttron center not show!!..page not found

![5 1](https://user-images.githubusercontent.com/30747120/35266397-3c2d2994-0049-11e8-8db1-1481c3f407e8.JPG)

CAN YOU HELP ME HOW TO GET THE SOLUTION ...

Thanks.....In Advance..

**Comment by craig8** [comment]
please use http://url:8080/vc/index.html

**Comment by vishuPPatel** [comment]
@craig8   Thanks For given me reply 👍 :)

**Comment by craig8** [comment]
@vishuPPatel Your welcome :)
