### ISSUE TITLE
PlatformAgent needs to go through manager addresses if first one fails

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#162]
Right now it just uses the first item of the list.

Based on #140

**Comment by craig8** [comment]
So the wording of this is interesting.  It leads me into thoughts of multiple VC's out there and collection nodes "picking" from the set of available VC's to manage it.

**Comment by jhaack** [comment]
If I remember correctly, this was originally multiple VIP interfaces to the same platform. Your comment would be an interesting possibility as well.

**Comment by jhaack** [comment]
OBE
