### ISSUE TITLE
VirtualEnv URL change breaks bootstrap process

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#1640]
VirtualEnv URL has changed again breaking the bootstrap process. This has happened before #600. Fork their repo or find some other solution to prevent this changing out from underneath us again.

**Comment by craig8** [comment]
The issue is caused because pypa/virtualenv hasn't released version 15.2.0 from their repo, however from https://pypi.python.org/pypi/virtualenv the latest reversion is 15.2.0.

The working around is modifying the get_version function to insert self.version="15.1.0" 

```` python
#Current
self.version = re.search(
    r'<revision>([^<]*)</revision>', doap_xml).group(1)
return self.version

# After
self.version = "15.1.0"
return self.version

````

**Comment by nmerket** [comment]
I'm running into this issue as well. I see the workaround and will use it until they update, but this seems like an overly fragile way to create a virtualenv.

**Comment by nmerket** [comment]
You could always pull it from PyPi directly, thereby avoiding the github/pypi version mismatch issue. Something like this:

```python
    f = urllib2.urlopen('https://pypi.python.org/pypi/virtualenv/json')
    r = json.load(f)
    if self.version is None:
        urls = r['urls']
    else:
        urls = r['releases'][self.version]
    tarball_url = None
    for url in urls:
        if url['packagetype'] == 'sdist':
            tarball_url = url['url']
            break
    assert(tarball_url is not None)
    self._fetch(tarball_url) # probably not quite right, but you get the idea
```

**Comment by jhaack** [comment]
Another workaround if you have virtualenv on the system already:

```
virtualenv --prompt='(volttron)' env
. env/bin/activate
python setup.py -e .
```

**Comment by nmerket** [comment]
For the record, what worked for me was

```
virtualenv --prompt='(volttron)' env
. env/bin/activate
pip install -e .
```

I still think downloading the package from pypi will be a more permanent solution to this problem.
