### ISSUE TITLE
Can not install bootstrap.py in volttron4

### ISSUE THREAD

**Issue by TPponmat** [VOLTTRON/volttron#1644]
error is "raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found"

Can not access link   "https://github.com/pypa/virtualenv/archive/''{}.tar.gz"

**Comment by craig8** [comment]
See issue #1640 

You say you are using volttron4.  From what url are you using?

**Comment by TPponmat** [comment]
I clone it at url https://github.com/VOLTTRON/volttron.git
and after that 
sudo apt-get update
sudo apt-get install build-essential python-dev openssl libssl-dev libevent-dev git
git clone https://github.com/VOLTTRON/volttron
cd volttron

but after I run python bootstrap.py. >> Error is 
"raise HTTPError(req.get_full_url(), code, msg, hdrs, fp) urllib2.HTTPError: HTTP Error 404: Not Found"

**Comment by craig8** [comment]
Thanks for that
 
You can use our release candidate by cloning using the following command

````
git clone https://github.com/VOLTTRON/volttron -b releases/5.0rc
````

The releases/5.0rc branch is far superior to the master branch.  In addition, it has the fix to the bootstrap that you are referencing from this issue.

**Comment by TPponmat** [comment]
What version of ubuntu(14 or 16 or 17)  and python (2.7.???) to recommend for volttron eleases/5.0rc .

**Comment by craig8** [comment]
We have used it on 12, 14, and 16 for ubuntu.  I am using it on mint 18 and it has been tested on centos as well.

**Comment by craig8** [comment]
This issue has been resolved in master please pull the latest version
