### ISSUE TITLE
Drivers do not recover after socket loss

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#165]
Remove network cable
Replace cable
Drivers publish empty messages as per #164

**Comment by kmonson** [comment]
I think I've fixed the publishing of empty messages. I haven't addressed
the driver recovery issue yet.

**Comment by kmonson** [comment]
Bleh, I fixed this a while ago in 66a19d16b0e24d5a43ebb6875ac71e419c4a4b7d.
