### ISSUE TITLE
bootstrap.py issue : doap no longer supported 

### ISSUE THREAD

**Issue by sonjinho** [VOLTTRON/volttron#1668]
### Description of Issue

They don't support doap
It says that the URL is no longer supported.
https://pypi.org/pypi?:action=doap&name=virtualenv

### Affected Version
master branch

### Screenshots
![issue](https://user-images.githubusercontent.com/7449344/38962386-03fa1de6-43a8-11e8-8239-dc31c750815e.png)

**Comment by craig8** [comment]
This issue has been solved in https://github.com/VOLTTRON/volttron/releases/tag/5.0.3  See #1674 which has been rolled out to master.
