### ISSUE TITLE
Periodic methods calls cease if the method raises an unhandled exception.

### ISSUE THREAD

**Issue by kmonson** [VOLTTRON/volttron#167]

**Comment by hashstat** [comment]
I don't think this should be considered a bug. The unhandled exception is likely to occur again in a subsequent run of the periodic. If that is the desired behavior, the agent developer should catch and log the exception.

I would actually recommend that unhandled exceptions in periodics be logged and then cause the agent to halt. But again, this should probably be explicitly handled by the agent developer. We want to be careful not to introduce too many automatic helps that may mask true errors or make them difficult to respond to.

Thoughts?

**Comment by kmonson** [comment]
I was bit by this when the driver's periodic scrape was failing and raising
an  exception that I did not catch. The current behavior kept the driver
from recovering when communication with the device was restored. I've now
handled it, but it was surprising way for the framework to act.

For me, the expected behavior is for the periodic to continue to be called
even if it fails. This is the behavior of frameworks like twistd and
tornado.

**Comment by hashstat** [comment]
After discussing the issue with the team, we agreed that wrapping the periodic call in a try-except block and logging the exceptions is probably the best approach.
