### ISSUE TITLE
Documentation build fails

### ISSUE THREAD

**Issue by shwethanidd** [VOLTTRON/volttron#1671]
Documentation build fails with error:
usage: sphinx-apidoc [OPTIONS] -o <OUTPUT_PATH> <MODULE_PATH> [EXCLUDE_PATTERN, ...]
sphinx-apidoc: error: unrecognized arguments: tests/**/* /home/volttron/git/volttron-2/volttron/lint

Error is observed with Sphinx version - 1.7.2
sphinx-apidoc command has to be executed with sequence of arguments

**Comment by schandrika** [comment]
fixed. created pull request #1672
