### ISSUE TITLE
YAML config loader chokes on tabs in JSON config files

### ISSUE THREAD

**Issue by acedrew** [VOLTTRON/volttron#1713]
NOTE issues are for bugs/feature requests not support.  Please ask at https://stackoverflow.com/questions/tagged/volttron for help

### Description of Issue
A tab in a legacy json file is not parsed as valid by the YAML parser.

### Affected Version

Develop

### Steps to Reproduce
Install agent with a JSON formatted config file that includes a tab character for readibility

**Comment by craig8** [comment]
@acedrew should fallback to the old way or search replace for /t and replace with spaces?  Thoughts?

**Comment by acedrew** [comment]
I think the best option is just to cascade to the previous parser on error, without writing your own YAML/JSON parser, there's no way to know whether a tab is part of a field or in the whitespace/syntax.

**Comment by craig8** [comment]
yup I agree...
