### ISSUE TITLE
Alternate Weather Service Needed

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#1728]
### Description of Issue
Weather Underground has been purchased and no longer provides free API keys. Existing keys are still usable but with no discussion on how long that will remain the case.

Researchers wishing to use the existing WeatherAgent will need to use existing keys or purchase new ones.

An alternative weather service should be identified and then a new WeatherAgent created to use that.

### Affected Version
All

### Additional Details
A potential (US Only) alternative is: 
https://www.weather.gov/documentation/services-web-api

Another solution will need to be found for non-US weather data.

**Comment by schandrika** [comment]
An new weather agent that queries data from weather.gov has been merged into develop. The current implementation does not support historical weather data. The base weather agent can be extended easily to any other weather provider.
