### ISSUE TITLE
RabbitMQ-VOLTTRON: Rerunning RabbitMQ setup causes error

### ISSUE THREAD

**Issue by nhill-cpi** [VOLTTRON/volttron#1730]
When I re-run `python volttron/utils/rmq_mgmt.py single` after already having successfully run it (because I wanted to see if I could reconfigure things using that same script), I get the following error after choosing to use the default rabbitmq configuration:

￼
![-_ppwhl3ig29p4rrx8go4vaopag_yqdqzuvngouisykn--pe8t7bhiutqlcy2ad2yigbu9_pqucrtgqmjpcz-gw1ckjzwtqcsjmwbnu9qydi_tzn0fkf2zfsmwjq88l2o](https://user-images.githubusercontent.com/32272907/42244714-ec925692-7eca-11e8-9c9f-cdac553a4267.png)

To reproduce: setup RabbitMQ for the first time by running `python volttron/utils/rmq_mgmt.py single` according to the README on the rabbitmq-volttron branch. Re-run `python volttron/utils/rmq_mgmt.py single` and choose to use the default rabbitmq configuration.

**Comment by shwethanidd** [comment]
This is fixed with VOLTTRON 6.0 alpha code changes
