### ISSUE TITLE
Volttron scripts that execute command as subprocess suppress error messages and return only cmd exit code

### ISSUE THREAD

**Issue by schandrika** [VOLTTRON/volttron#1801]
In many utility scripts we use the below code to execute commands to install/remove/configure agents. T
``
process = subprocess.Popen(cmds, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
 process.wait
``
This suppresses errors and should be replaced with code that handles stdout and stderr.  We can suppress stdout if verbose==False but always output errors.

**Comment by shwethanidd** [comment]
@schandrika has this been fixed? I don't think rabbit branch has the fixes yet.

**Comment by schandrika** [comment]
There are 2 PR for this. One for develop and one for rabbitmq branch
