### ISSUE TITLE
RabbitMQ-VOLTTRON:Pointing to a new volttron home and starting volttron fails

### ISSUE THREAD

**Issue by schandrika** [VOLTTRON/volttron#1802]
Pointing to a new volttron home directory and running ./start-volttron fails because RMQMgmt class is being instantiated always, which in turn expects a volttron instance name in the config. So code throws an error "No instance name is configured". 
This is not a ZMQ requirement and hence a user should be able to start-volttron with ZMQ without a volttron config file.

**Comment by shwethanidd** [comment]
Closing old issue
