### ISSUE TITLE
ERROR: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by sumanth13** [VOLTTRON/volttron#181]
I am trying to launch the Demand Response agent but I received this error. Can you please help me?
![screenshot from 2015-09-16 12 42 00](https://cloud.githubusercontent.com/assets/14006782/9911579/c90b0342-5c70-11e5-97ca-63ef8656178c.png)

**Comment by hashstat** [comment]
It looks like you discovered a bug in the error handling during configuration. :-(  The real error is that the file does not exist. Do `ls Agents/DemandResponseAgent/*.launch.agent` to list the available configuration files. We will add this to our list of outstanding bugs. Thanks.
