### ISSUE TITLE
Make device get and set errors consistent.

### ISSUE THREAD

**Issue by kmonson** [VOLTTRON/volttron#182]
Modbus and BACnet do different things when there is a failure to set a point IFF the points are not configured to writable.

Modbus returns none. BACnet raises an exception.

**Comment by kmonson** [comment]
Oh, and BACnet does the right thing. Modbus needs to be fixed.

**Comment by jhaack** [comment]
Is this still an issue?

**Comment by craig8** [comment]
@kmonson modbus needs to be fixed? I am going to put this into a 4.1 cycle for you @kmonson

**Comment by kmonson** [comment]
I'll look into this with the MODBUS fixes.

**Comment by craig8** [comment]
Please create an epic and reference all of the things related to devices
