### ISSUE TITLE
[Feature Request] Schedule agent functions with cron like schedules

### ISSUE THREAD

**Issue by dmossie** [VOLTTRON/volttron#1823]
When building an agent it would be awesome to schedule agent functions with cron like schedules.

Example:
```
@Core.cron('0 1 * * *')
def foo(self):
    ...

```

**Comment by hashstat** [comment]
I think it would be nice to have a more generic decorator, or an overloaded `periodic` decorator, that takes an iterable of datetime objects.

Example:
```python
from volttron.platform.agent import cron

@Core.periodic(cron('0 1 * * *'))
def foo(self):
    ...
```
One could easily replace `cron()` with another generator, list, or other iterable to produce the desired schedule.

Perhaps it could also accept an iterable of floats/ints to produce more a more varied/customized periodic execution than what is currently possible.

**Comment by hashstat** [comment]
I looked into this and found the schedule decorator/method to be a more appropriate candidate. In fact, it can be used to replace the periodic decorator/method as well.

```python
from volttron.platform.agent import cron
from volttron.platform.vip.agent import periodic

@Core.schedule(cron.schedule('0 1 * * *'))
def foo(self):
    ...

@Core.schedule(periodic(20))
def bar(self):
    ...
```

A patch is forthcoming.

**Comment by craig8** [comment]
@dmossie I am going to close this as it is now in the develop branch.
