### ISSUE TITLE
Alerts on restored agent's health

### ISSUE THREAD

**Issue by tnesztler** [VOLTTRON/volttron#1826]
### Description of Issue
The next section assumes you're subscribed to the `alerts` topics (see [here](https://github.com/VOLTTRON/volttron/blob/dd90b75b161672e16906cebca2a9210e7f2ef419/volttron/platform/messaging/topics.py#L82)).
For an agent using the health subsystem (such as all historian agents based on the `BaseHistorian` class), if the health goes from GOOD to BAD (for example due to this [case](https://github.com/VOLTTRON/volttron/blob/dd90b75b161672e16906cebca2a9210e7f2ef419/volttron/platform/agent/base_historian.py#L1074)), a message is published as expected.
However, whenever the agent starts publishing again, the health is restored to GOOD but no message is sent stating so.

One use case is an agent publishing the status of selected agents to a Slack channel. It is impossible to know if the agent's status is still BAD or was restored.

### Affected Version
5.1 and up

### Screenshots
<img width="1382" alt="screen shot 2018-10-22 at 4 07 45 pm" src="https://user-images.githubusercontent.com/25331241/47297173-a58d7000-d614-11e8-882c-8a7dda8fb248.png">
In this screenshot, data is published every 5 minutes.

#### Expected
Message being published to the `alerts` base topic or "subtopics" at each change of the health of an agent using the health subsystem. 

#### Actual
Only degraded health is reported to the `alerts` topic. 

### Steps to Reproduce
1. Use an agent that is based on the BaseHistorian agent and subscribe to `alerts`.
2. Prevent the historian to publish data. Wait for its health to go from GOOD to BAD. A new message is published.
3. Let the historian publish again. The health should go from BAD to GOOD again after the data backlog have been processed. No message is being published once the health is restored.

**Comment by schandrika** [comment]
Fixed as part of #1846.  If status becomes bad after the initial setup phase, say a connection failure when trying to write device data to database, then once the connection is back up, database write will happen and status of agent will change to GOOD.  If connection failure happens at the time of startup (agent init, startup) then alert is sent to user and user need to fix the issue and restart the agent.
