### ISSUE TITLE
Numpy Import Error

### ISSUE THREAD

**Issue by kl5pierce** [VOLTTRON/volttron#1831]
NOTE issues are for bugs/feature requests not support.  Please ask at https://stackoverflow.com/questions/tagged/volttron for help

### Description of Issue

When attempting to run pytests for rabbitmq pubsub while in the ~/volttron directory, the test recieves ImportErrors, indicating that numpy needs to be imported, when test should be able to run without ImportErrors.

### Steps to Reproduce
```
cd ~/volttron
python bootstrap.py --testing
pytest -s -k test_granularity
```

### Additional Details

[additional_details_numpy_output.txt](https://github.com/VOLTTRON/volttron/files/2526763/additional_details_numpy_output.txt)

Temporary fix: `pip install numpy`

Note: if you go to the directory of the pytest:
`/home/username/volttron/volttrontesting/subsystems`

can run `pytest -s -k test_granularity` with no issues.

**Comment by craig8** [comment]
what is test_granularity?  Where is it located?

**Comment by kl5pierce** [comment]
/home/username/volttron/volttrontesting/subsystems in the rabbitmq-volttron branch.

**Comment by craig8** [comment]
not finding it here https://github.com/VOLTTRON/volttron/tree/rabbitmq-volttron/volttrontesting/subsystems

**Comment by kl5pierce** [comment]
My bad. It's one of the tests in https://github.com/VOLTTRON/volttron/blob/rabbitmq-volttron/volttrontesting/subsystems/test_rmq_pubsub.py

**Comment by kl5pierce** [comment]
Quick note. The file that was initially causing the ImportError was located in: ~/volttron/services/core/OpenADRVenAgent/test/ControlAgentSim/controlagentsim/agent.py. However, the error can be fixed by modifying ~/volttron/optional_requirements.json
