### ISSUE TITLE
RabbitMQ-VOLTTRON: Unclear error message on YAML parse error

### ISSUE THREAD

**Issue by shwethanidd** [VOLTTRON/volttron#1864]
### Description of Issue
If there is syntax error in rabbitmq_config.yml, the default error message logged is "Error opening /home/volttron/.volttron/rabbitmq_config.yml. Please create a rabbitmq_config.yml...." which is misleading to the user.
Instead an appropriate log message indicating that there is syntax error in the yml file should be logged.

**Comment by shwethanidd** [comment]
@kl5pierce Can you work on this.

**Comment by kl5pierce** [comment]
Yes. Will start working on it now.
