### ISSUE TITLE
Can't run volttron-cfg when Volttron is installed offline (w/o Git)

### ISSUE THREAD

**Issue by tnesztler** [VOLTTRON/volttron#1887]
### Description of Issue
When you don't have Internet access at all, you can install Volttron by downloading the files from GitHub as a zip and all Linux_x86_64 dependencies from pypi (in the requirements.py + virtualenv + wheel==0.30) on another system with Internet access, move the files over and install it manually (w/ bootstrap.py --offline once the virtualenv created and dependencies installed).
However when it comes the time to configure it, you are stuck because there isn't a `.git` folder inside the main directory (only a `.github` one)
This process get stuck on this [function](https://github.com/VOLTTRON/volttron/blob/58b015c1e6f62fc1cf7151f4dd44a5a81bd295e0/volttron/platform/instance_setup.py#L139)

### Affected Version
master (5.1.0)

#### Expected
The code should rely on other data points to detect the Volttron root folder.

#### Actual
The code rely on the `volttron` and `.git` folder. However the `.git` folder might not be present.

### Steps to Reproduce
- Remove `.git` folder if present inside volttron root folder
- Active environment
- Run `vcfg`

Currently you can create a dumb `.git` folder to make it work but it isn't user friendly for a "newcomer" since the error message doesn't tell you what is clearly wrong.

**Comment by craig8** [comment]
@tnesztler thanks for the report!  It's now fixed in the latest develop.
