### ISSUE TITLE
Agenda for 10/16 office hours

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#194]
Use this issue to gauge interest in topics for the next office hours.

Vote for an existing topic or add a comment with a new one. Voting can be done with a comment that is just "+1" or through use of the ZenHub Chrome plugin: https://www.zenhub.io/.

**Comment by jhaack** [comment]
Detailed discussion/walkthrough of VOLTTRON drivers: how to set them up, how to write your own.

**Comment by jhaack** [comment]
VIP discussion. How does it work and what can I do with it?

**Comment by jhaack** [comment]
Security: How do I use the security features of VOLTTRON to protect my deployment. Also, how do I temporarily disable them when I am exploring VOLTTRON or doing local development.

**Comment by jhaack** [comment]
Agent Development walkthrough: Use the ListenerAgent as a jumping off point to discuss agent development and the utilities that support it.

**Comment by craig8** [comment]
A discussion of how to use the VolttronCentral agent to call a function on a remote platform.  As well as using the web api through python scripts.

**Comment by MKSahm** [comment]
VIP discussion. How does it work and what can I do with it?

**Comment by sumanth13** [comment]
VIP Discussion. 
how to use it with OpenADR and DR agent

**Comment by jhaack** [comment]
VOLTTRON Applications: What are people doing with VOLTTRON?
