### ISSUE TITLE
Registering platforms is prone to user error when encryption and authentication are enabled

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#198]
It's very easy to get things wrong/mismatched when using encryption and security. This combined with no error message presented to the user can be frustrating.

**Comment by craig8** [comment]
In 4.0 we made huge strides for this.  I am going to continue and try to make it as seamless as possible

**Comment by jhaack** [comment]
Yes, auto-register takes care of a majority of the cases.

**Comment by craig8** [comment]
Actually with vcp -> vc working it is seamless so i am going to close this :)
