### ISSUE TITLE
Regular expression topic matching

### ISSUE THREAD

**Issue by hashstat** [VOLTTRON/volttron#207]
Implement the ability to match pub/sub topics by regular expression. Currently, only prefix matching is supported forcing agent authors to subscribe to the shortest static prefix and then do regex matching in the topic handler. The ideal solution is to allow sending the regular expression to the holder of the pub/sub bus so that only messages matching the regex are returned. One way to do this is to only use regular expressions and transform prefix matching strings into a regex. Another way is to support both prefix and regex matching using some distinguishing syntax.

Updating the matching module to support regular expressions will allow agent authors to easily subscribe using decorators (keep in mind 2.x compatibility).

**Comment by jhaack** [comment]
Moving to rabbit. Re-examine if need arises.
