### ISSUE TITLE
Add VIP authorization support

### ISSUE THREAD

**Issue by hashstat** [VOLTTRON/volttron#208]
Now that authentication is supported, capabilities and roles can be assigned to authentication tokens. RPC methods should be exported by the auth service to allo these capabilities and roles to be retrieved by agents using the user-id attached to VIP messages. The capabilities and roles can then be used to authorize access to RPC calls and other subsystem operations. Decorators can also be created to easily mark the access level of exported RPC methods.

I recommend a default deny policy. Credentials could be cached for a short time to improve efficiency.

**Comment by zbeech** [comment]
1. Authorization should be as simple as possible on the same platform instance (server).
  * Public key should be provided from server to client via an API (TBD)

**Comment by fstshrk** [comment]
Security threats that we are defending against on a single platform are:

1) Agents can not spoof each other/
2) Agents can not listen or write to topics that they are not authorized

**Comment by craig8** [comment]
volttron discovery protocol

**Comment by zbeech** [comment]
Authorization has been merged in for a while now.
