### ISSUE TITLE
stop-volttron script fails to shutdown volttron platform

### ISSUE THREAD

**Issue by jklarson** [VOLTTRON/volttron#2126]
### Description of Issue
Running the stop-volttron script fails to shutdown the platform. There are no error messages in volttron.log, and the "closing connection to ZMQ" text displays as though it were shutting down, however the platform is still running.

### Affected Version
all-strings-python3 branch for 7.0 release

### Screenshots
![image](https://user-images.githubusercontent.com/40306657/66528332-543ff000-eab4-11e9-8572-b274ae6df81b.png)

### Steps to Reproduce
start volttron platform using zmq on all-strings-python3 branch

Have not tried RMQ, will try to reproduce using RMQ

**Comment by schandrika** [comment]
Fixed bytes/string conversion and default user-id expected by main.py when trying to shutdown platform. This also took care of vcfg errors

**Comment by shwethanidd** [comment]
@schandrika this is fixed right?

**Comment by schandrika** [comment]
This looks like a timing issue. vctl shutdown --platform (and hence the wrapper stop-volttron) is not waiting till platform shutdown is complete.
