### ISSUE TITLE
3.7+ python gevent.async issue

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#2144]
Python 3.7 introduced a new async keyword so we need to work around that with gevent.

**Comment by liamdiprose** [comment]
gevent renamed the `async()` method to `async_()`. [gevent changelog](http://www.gevent.org/changelog.html#id18)

This diff makes `mypy` happy, but I'm unable to confirm it works due to other errors:

https://github.com/VOLTTRON/volttron/compare/volttron-7-preview...pba-nz:async-is-a-keyword
