### ISSUE TITLE
Historians should use timestamps with no timezone to avoid dbapi2 bug

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#216]
The bug in #174 has been worked around but #91 will still affect those using Python 2.7.3. The way to avoid this is to use timestamps without timezones for storage into the database.

**Comment by jhaack** [comment]
Currently this is documented here: https://github.com/VOLTTRON/volttron/wiki/FAQ#id3

**Comment by kmonson** [comment]
A better solution is to stop using python sqlite3 datetime parsing terribleness. 

I think we can do this without breaking existing sqlite3 historians (and base historians) by registering our own datetime parser regardless of python version. We probably don't need to create a new converter just a new parser that will use dateutil parse when we grab it back out.

**Comment by kmonson** [comment]
https://docs.python.org/2/library/sqlite3.html#converting-sqlite-values-to-custom-python-types

We can replace the existing parser with our own.

**Comment by kmonson** [comment]
Fixed in 7d803b3ec3f076d7809955160b0fd986d81461fc

Will make it into develop soon.
