### ISSUE TITLE
Actuator 3.0 cannot interact with 2.0 agents

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#217]
The Actuator in 3.0 cannot interact with 2.0 agents. This should be documented with an example of how to transition agents to talk to the 3.0 Actuator. Alternatively, enhance the actuator to work with legacy applications.

**Comment by craig8** [comment]
Can we get a status on this @kmonson

**Comment by kmonson** [comment]
We should test it again. During Actuator testing we discovered the
techniques used to deal with 2.0 agents was incorrect. We fixed it to use
the utility functions for dealing with 2.0 compatibility but have not had
an opportunity to test it.
