### ISSUE TITLE
Bacpypes 0.17.7 breaks bacnet_scan and grab_bacnet_config in scripts in volttron-7-preview

### ISSUE THREAD

**Issue by jklarson** [VOLTTRON/volttron#2171]
### Description of Issue
After running bootstrap, bacpypes version 0.17.7 is installed, which features breaking changes for scripts/bacnet_scan.py and scripts/grab_bacnet_config.py

### Affected Version
volttron 7.0, volttron 7 preview branch

### Additional Details
Both scripts use bacpypes.service.device LocalDeviceObject which was removed in 0.17.7

**Comment by kwarodom** [comment]
Same issue i faced yesterday when installing Volttron 7 for the first time since the preview version released. I installed Bacpypes 0.16.7 and it works as LocalDeviceObject was removed in 0.17.7 as you mentioned

**Comment by shwethanidd** [comment]
@jklarson can you close the issue if resolved
