### ISSUE TITLE
Allow configuration option to limit the publishing level

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#218]
Currently publishing of device data happens 4 different ways.  It would be great if you could customize the publishing to be either breadth first/depth first or just publish the all or just publish the points.

**Comment by craig8** [comment]
@kmonson status?

**Comment by kmonson** [comment]
Sorry, this was done in 07ec6783176341246a3b7727997cc8a773575d08 and I forgot to close this.
