### ISSUE TITLE
Can anyone develop and test on VSCODE ?

### ISSUE THREAD

**Issue by Soulweed** [VOLTTRON/volttron#2195]
NOTE issues are for bugs/feature requests not support.  Please ask at https://stackoverflow.com/questions/tagged/volttron for help

**Comment by craig8** [comment]
I am not sure this is the right place for this type of question, however the answer is yes.  There is no requirements on using pycharm, eclipse, vim or any other ide in order to run VOLTTRON.  If I have miss understood your question then please reopen this.
