### ISSUE TITLE
vcfg unclean shutdown

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#2214]
### Description of Issue

![image](https://user-images.githubusercontent.com/3979063/74118742-a4c27980-4b8a-11ea-9613-b5cf9da267dc.png)

It seems as if the volttron process should be killed if the vcfg does not finish or someone control c's out of it.

Note that the binding is still blocked with this, however there isn't a volttron present in ps.  The vcfg is relying on state somewhere other than the actual processes.  

To get out of this state remove $VOLTTRON_HOME

### Affected Version
develop

**Comment by shwethanidd** [comment]
@sgilbride  can you point to the right PR and close this issue?

**Comment by sgilbride** [comment]
Fixed in #2233
