### ISSUE TITLE
forwarder doesn't attempt to reconnect

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#2217]
### Description of Issue
![image.png](https://images.zenhubusercontent.com/55b9aef64f7a08fbb7f3fd50/1f06ca5a-10d9-4b4e-a258-6d249e65f3e4)

After accepting the forwarders publickey through the web interface the forwarder doesn't auto reconnect.  This is probably due to a timeout on the connection side of the forwarder and it not properly continuing to request access.

This should be handled in auth subsystem, however if the connection fails during the setup it seems that the agent just dies.

**Comment by shwethanidd** [comment]
Not observing this behavior in latest develop
