### ISSUE TITLE
Actuator Agent still writes to point even if requester does not have a lock.

### ISSUE THREAD

**Issue by kmonson** [VOLTTRON/volttron#223]
The Actuator Agent will still correctly report an error, but the point is written anyway.

**Comment by kmonson** [comment]
$$RELEASE_NOTE 

Fixed Actuator device locking not actually locking anything.

NOTES

Even though the ActuatorAgent would report a lock error if an Agent had not scheduled anything, set requests would still go through. This is now fixed.

**Comment by kmonson** [comment]
I think I've already fixed this. I need to check.

**Comment by craig8** [comment]
You did. It's under the Fixed message above.

Sent from my iPad

On Nov 23, 2015, at 9:10 PM, kmonson <notifications@github.com<mailto:notifications@github.com>> wrote:

I think I've already fixed this. I need to check.

**Comment by kmonson** [comment]
Didn't follow the link and I'm still in a fever induced haze...
