### ISSUE TITLE
Update Joining the Community page

### ISSUE THREAD

**Issue by RichardLitt** [VOLTTRON/volttron#2254]
### Description of Issue

The link to the Slack channel sign up leads to a 404 on the Community page [here](https://github.com/VOLTTRON/volttron/blob/develop/docs/source/community_resources/index.rst). As well, https://volttron-community.slack.com/ suggests that I need a limited subset of possible emails in order to Sign up for an account. If this is the case, I would suggest removing the Slack section from this page, as it is a closed group.

### Affected Version

Develop.

**Comment by jklarson** [comment]
@jhaack @shwethanidd What would you guys like to see here?

**Comment by jklarson** [comment]
Fixed in #2446
