### ISSUE TITLE
Show status of platforms in side frame on VC pages

### ISSUE THREAD

**Issue by jchap-pnnl** [VOLTTRON/volttron#228]
Add a side-panel to VC that shows the status of all registered platforms. 

- [ ] Build calls in VOLTTRON Central to populate data in the panel for platforms, agents, devices, data points, etc.
- [x] Add visualization to convey statuses of good, bad, and unknown.
- [x] Allow the platforms to be sorted by status.
- [x] Implement tree structure with children nested under parents.
- [x] Allow filtering the tree based on search terms.
- [x] Get data for each item by hovering over it.
- [x] Check a box next to the item to add the item to a graph.

**Comment by jchap-pnnl** [comment]
# The call to get platform statuses will return a list of objects the following structure: 
{
    "result": [{
        "platform.uuid": "0987fedc-65ba-43fe-21dc-098765bafedc",
        "status": "GOOD"
    },
    {
        "platform.uuid": "2291fedc-65ba-43fe-21dc-098765bafedc",
        "status": "BAD"
    },
    {
        "platform.uuid": "4837fedc-65ba-43fe-21dc-098765bafedc",
        "status": "UNKNOWN"
    }]
}

**Comment by jchap-pnnl** [comment]
We need calls to get statuses of platform agents, platform devices, and their points, so we can get statuses of children as we drill into the panel tree.

To get the platform agent statuses, use the following call:

POST /jsonrpc
{
    "jsonrpc": "2.0",
    "method": "platforms.uuid.0987fedc-65ba-43fe-21dc-098765bafedc.receive_agent_statuses",
    "authorization": "someAuthorizationToken",
    "id": #
}

The call will return a list of objects with the following structure: 
{
    "result": [{
        "agent.uuid": "0987fedc-65ba-43fe-21dc-098765bafedc",
        "agent.name": "SqlHistorian",
        "status": "GOOD"
    },
    ....]
}

To get the platform device statuses, use the following call:

POST /jsonrpc
{
    "jsonrpc": "2.0",
    "method": "platforms.uuid.0987fedc-65ba-43fe-21dc-098765bafedc.receive_device_statuses",
    "authorization": "someAuthorizationToken",
    "id": #
}

The call will return: 
{
    "result": [{
        "device.uuid": "0987fedc-65ba-43fe-21dc-098765bafedc",
        "device.name": "RTU2",
        "status": "GOOD"
    },
    ....]
}

To get the device points, use the following call:

POST /jsonrpc
{
    "jsonrpc": "2.0",
    "method": "device.uuid.0987fedc-65ba-43fe-21dc-098765bafedc.receive_device_points",
    "authorization": "someAuthorizationToken",
    "id": #
}

The call will return:
{
    "result": [{
        "point.uuid": "0987fedc-65ba-43fe-21dc-098765bafedc",
        "point.name": "CoolingValvePosition",
        "status": "GOOD"
    },
    ....]
}

**Comment by craig8** [comment]
We haven't finished this yet as the calls aren't there yet

**Comment by jchap-pnnl** [comment]
Clicked the wrong button to comment.

**Comment by jchap-pnnl** [comment]
I've updated the general_definition.json to show statuses and other information for populating the platforms status panel.

[general_definition.json.txt](https://github.com/VOLTTRON/volttron/files/83352/general_definition.json.txt)

**Comment by jchap-pnnl** [comment]
Based on our latest discussions, the tree will have the following structure:

-- platforms
    -- points
    -- agents
    -- buildings
        -- points
        -- devices
            -- points
            -- devices

**Comment by jchap-pnnl** [comment]
Modified tree structure:

* platforms
 * topics
 * agents
 * sites
    * points
    * buildings
      * points
      * devices
        * points
        * devices

**Comment by jchap-pnnl** [comment]
Example of above structure:

* Main-VC
  Points
  * CpuIdleTime
  * CpuIoWait
  Agents
  * ListenerAgent-3.0
  * SqlHistorian-3.0.1
  * VoltronCentralAgent-3.0
* WSU
  Points
  * OutdoorAirTemperature
  Buildings
  * BSEL
    Points
    * LightingStatus
    * WholeBuildingElectricity
    Devices
    * AHU
      Points
      * DuctStaticPressureSetPoint
      Devices
      * Zone
        Points
        * TerminalBoxDamperCommand
        * ZoneTemperature
  Agents
  * PlatformAgent
  * SQL-Historian
