### ISSUE TITLE
VOLTTRON 6.0 installation and start platform error 

### ISSUE THREAD

**Issue by geyin96** [VOLTTRON/volttron#2281]
When I installed and started VOLTTRON 6.0 platform, the error occurs:
<img width="648" alt="Screen Shot 2020-04-03 at 5 20 57 PM" src="https://user-images.githubusercontent.com/29635351/78414073-62e10d00-75e8-11ea-8cfb-a725030f378e.png">
And I found during the VOLTTRON installation, the only error is reported:
<img width="644" alt="Screen Shot 2020-04-03 at 7 41 21 PM" src="https://user-images.githubusercontent.com/29635351/78414095-83a96280-75e8-11ea-94ed-a6615ac9575b.png">
Then I reinstalled pyopenssl with compatible version of cryptography
`sudo pip install pyopenssl --upgrade cryptography`
however, the error still exists.
<img width="651" alt="Screen Shot 2020-04-03 at 8 23 12 PM" src="https://user-images.githubusercontent.com/29635351/78414194-fc102380-75e8-11ea-8a5d-68a6b0d48135.png">

**Comment by craig8** [comment]
The last image indicates that you have another instance running.  Please run 

````
ps aux |grep volttron

# Then kill the volttron 
kill procid
````

**Comment by craig8** [comment]
assuming this is no longer an issue....
