### ISSUE TITLE
caching and reliability

### ISSUE THREAD

**Issue by alliao-lbl** [VOLTTRON/volttron#23]
We have a project where we want to guarantee reliability for receiving messages sent through the Volttron message bus.  For example, if a receiving agent misses a critical message, we want to set up a way to cache messages. The recipient agent would indicate it missed the message and another agent or service could send the requested message.  Is that a capabilty built into Volttron?  Or how would you recommend implementing this functionality?

**Comment by craig8** [comment]
The historians now provide caching of messages to specific points (devices/*/all, datalogger/* etc.). I think one of those would be a good starting point.

**Comment by jhaack** [comment]
Closing for now. Can revisit during Message Bus enhancement
