### ISSUE TITLE
Incorporate feedback on UI for registering platforms and removing agents

### ISSUE THREAD

**Issue by jchap-pnnl** [VOLTTRON/volttron#230]
- [x] Adjust the layout in the registering platforms dialog box so the preview and buttons are visible without scrolling. (Eliminate the scrolling.)

- [x] Style the preview box so it doesn't look editable.

- [x] Put the address field next to the protocol selector.

**Comment by craig8** [comment]
Ajust the layout so that the serverkey, public and secret are all the same length and the minimum length should be what we get from the output of volttron-ctl keypair.  Two examples of that are

**Comment by craig8** [comment]
I thought I would post what the new registration page looks like.
![platform_registration](https://cloud.githubusercontent.com/assets/3979063/11284269/b17e682a-8ebd-11e5-809f-eeaca9b8a6c8.png)

**Comment by jchap-pnnl** [comment]
$$RELEASE_NOTE

UI updates to remove agent and register platform

NOTES

To remove an agent from a platform, click the Remove button in the row for that agent and confirm the removal. 

In the register-platform form, there are separate fields for the protocol, address, and encryption and authentication keys. The platform can be registered without any keys, with a server key only, or with all three -- a server key, public key, and secret key. The full concatenation of the protocol, address, and keys appears in a preview field as the values are entered.
