### ISSUE TITLE
NotFound Error While Trying to Access the Administration Area

### ISSUE THREAD

**Issue by gunduru** [VOLTTRON/volttron#2317]
### Description of Issue
Links for the Web GUI is broken for both https and http setup. Online documentation also mentiones /vc/index.html but this is not present either
https://localhost:8443/admin/login.html
http://localhost:8080/admin/login.html

### Affected Version
Latest

### Screenshots
![Screen Shot 2020-04-21 at 12 54 15](https://user-images.githubusercontent.com/4470766/79852481-625dba00-83cf-11ea-9d95-b76482a98b4f.png)

#### Expected
A login page is expected

#### Actual
not found page

### Steps to Reproduce
1. Fresh install from github master
2. vcfg for a central instance
3. start volttron
4. reach default welcome page
5. click the administration area link and you get not found

**Comment by craig8** [comment]
@gunduru Please make sure you are using develop or the 7 pre release  not master as v7 hasn't been pushed to master as of yet.

**Comment by gunduru** [comment]
Thanks a lot, just tried with releases/7.x branch and it's working now

**Comment by craig8** [comment]
@gunduru Awesome! Glad it works for you!
