### ISSUE TITLE
Agent upgrade is failing

### ISSUE THREAD

**Issue by shwethanidd** [VOLTTRON/volttron#2318]
Agent upgrade is failing with following error. The existing agent is successfully removed but entry in auth.json is not removed. So when new agent with same VIP identity is installed, the agent shuts down as this VIP identity is already in the auth file.

File "scripts/install-agent.py", line 387, in <module>
    install_agent(opts, opts.package, opts.config)
  File "scripts/install-agent.py", line 149, in install_agent
    err_prefix="Error installing agent")
  File "/home/vuzer/volttron/volttron/platform/agent/utils.py", line 773, in execute_command
    raise RuntimeError()
RuntimeError

### Affected Version
releases/7.x

**Comment by craig8** [comment]
@shwethanidd when upgrading agents, the auth shouldn't be removed....Imagine you have a vpc that is connecting to an external platform.  You want the auth to remain without having to re authorize that external agent!

**Comment by shwethanidd** [comment]
@craig8 PR#2319 fixes the issue, can you review?

**Comment by shwethanidd** [comment]
Review done
