### ISSUE TITLE
Both SQLHistorian and Forwarder agents can not create its sqlite database 

### ISSUE THREAD

**Issue by rkini-pnnl** [VOLTTRON/volttron#2322]
### Description of Issue
Both the SQLHistorian and Forwarder agents can not create its SQLite database on Fedora 31 and Ubuntu 19.10.

### Affected Version
Volttron develop branch
releases/7.x

#### Expected

![image](https://user-images.githubusercontent.com/61986575/80045860-8e576900-84bd-11ea-91d1-81814ac5dcd8.png)

#### Actual
We get empty sqlhistorianagent-<version>-data directory, as shown below, for both forwarder and SQLHistorian agent:

![image](https://user-images.githubusercontent.com/61986575/80045371-0886ee00-84bc-11ea-8ae7-3778c3ef1e1d.png)

### Steps to Reproduce
Install SQLHistorian agent with the default configuration on Ubuntu 19,10

**Comment by UTGrid** [comment]
It is visible in the tree, but bears adding that the agent does successfully create a data directory when started. The historian.sqlite file, however is not added to the data directory after it is added.

**Comment by davidraker** [comment]
It is visible in the tree, but bears adding that the agent does successfully create a data directory when started. The historian.sqlite file, however is not added to the data directory after it is added.

**Comment by shwethanidd** [comment]
Resolved in #2346
