### ISSUE TITLE
"vctl auth serverkey" command returns timed out

### ISSUE THREAD

**Issue by rkini-pnnl** [VOLTTRON/volttron#2323]
### Description of Issue
The “vctl auth serverkey” command returns “operation timed out”. However, other auth commands work fine.

### Affected Version
volttron develop branch
releases/7.x

### Screenshots
![image](https://user-images.githubusercontent.com/61986575/80046151-96fc6f00-84be-11ea-9584-774a58d51f2a.png)

### Steps to Reproduce
use ubuntu 19.10 version

**Comment by shwethanidd** [comment]
Resolved in #2346
