### ISSUE TITLE
Very slow output from "vctl status" command

### ISSUE THREAD

**Issue by rkini-pnnl** [VOLTTRON/volttron#2324]
### Description of Issue
"vctl status" command output waits a few seconds between each listed agent.

### Affected Version
volttron develop branch
releases/7.x

### Steps to Reproduce
You can reproduce it with ubuntu 19.10 and Fedora 31.

**Comment by shwethanidd** [comment]
Has the same underlying issue as #2320

**Comment by craig8** [comment]
@shwethanidd are you sure its the same issue?

**Comment by shwethanidd** [comment]
Resolved in #2346
