### ISSUE TITLE
Auth does not get list of peers connected to the platform during startup

### ISSUE THREAD

**Issue by shwethanidd** [VOLTTRON/volttron#2345]
# Description of Issue
During platform startup AuthService agent reads auth.json and attempts to send agent capabilities message to all the agents connected to the platform. AuthService agents tries to get list of agents using peerlist(). Peerlist() fails silently with gevent timeout error.

volttron.log shows below statement

2020-05-18 15:14:18,143 () volttron.platform.auth WARNING: Attempt 1 to get peerlist failed with exception

Related to issue #2119

### Affected Version
7.0 rc

**Comment by craig8** [comment]
@shwethanidd will be hiding it if it is only when the platform ffirst starts!
