### ISSUE TITLE
Provide context in Readme

### ISSUE THREAD

**Issue by anselmbradford** [VOLTTRON/volttron#235]
Consider linking to http://gridoptics.pnnl.gov/VOLTTRON/ from the github org page and the repository website field.

Please update `README.md` to provide a layman's explanation of the project, as well as installation and contribution guidelines. See http://github.com/cfpb/open-source-project-template for inspiration.

**Comment by xaviershay** [comment]
I would like this but am too new to contribute myself :)

**Comment by xaviershay** [comment]
I found https://github.com/VOLTTRON/volttron/wiki

**Comment by jhaack** [comment]
Committed to develop
