### ISSUE TITLE
Master Driver global override stores devices as lower case but should be case sensitive to properly affect override

### ISSUE THREAD

**Issue by rlutes** [VOLTTRON/volttron#2394]
NOTE issues are for bugs/feature requests not support.  Please ask at https://stackoverflow.com/questions/tagged/volttron for help

### Description of Issue
The values in self.instances and path value passed to set_point (and it's derivatives) and revert_point (and it's derivatives) is case sensitive.   Line 578 and line 586 (w.r.t master branch) of agent.py for MasterDriverAgent calls .lower() on both device name and pattern for override.  Then stores the overridden device as lower case.  If failsafe_revert is True, an exception will occur when self.instances[name] is call on if the device name is not naturally lowercase.

I fixed this issue by removing the .lower() call on lines 578, 586, 663, 675. 

### Affected Version
master, develop

**Comment by craig8** [comment]
#2422
