### ISSUE TITLE
Create script to gather release notes since last release

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#249]
- [x] Because github imposes a restriction on the number of requests that can be made, we need to allow user to login to github itself.  Prompt for username/pass[key] on the command line.
- [x] Interrogate the google api asking for the issues with $RELEASE_NOTES in the body of the issue since the last release.

- [ ] Make a useful report from this data so that it can be easily trimmed into a new release. (note see the feature/release-process branch (release_notes.py file).  Craig will give you more insite.

**Comment by jhaack** [comment]
Could you take another look at this

**Comment by craig8** [comment]
OBE
