### ISSUE TITLE
VOLTTRON 7.x bootstrap fails because of greenlet and idna version mismatch.

### ISSUE THREAD

**Issue by schandrika** [VOLTTRON/volttron#2618]
### Description of Issue
VOLTTRON 7.x bootstrap fails because of greenlet and idna version mismatch

### Affected Version
VOLTTRON 7.x

### Additional Details
This happens because greenlet and idna were downloaded automatically by requests package as depenedcies. requests package is pinned to specific version but latest version of greenlet and idna are not compatible with pinned version of requests package

**Comment by schandrika** [comment]
Fixed in volttron 7 release branch

**Comment by shwethanidd** [comment]
Fixed in releases/7.x and releases/7.0.1 branch
