### ISSUE TITLE
See if we should use reactd3 graphing library

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#263]
Http://reactd3.org

In addition there is another way that might be better/worse depending on what we are attempting to accomplish.

http://oli.me.uk/2015/09/09/d3-within-react-the-right-way/

**Comment by craig8** [comment]
@jchap-pnnl not sure if we did this or not...thinking so as we are doing stuff :) close if not necessary..

**Comment by jchap-pnnl** [comment]
We implemented the nvd3 charting library instead of reactd3.
