### ISSUE TITLE
Volttron Not Starting

### ISSUE THREAD

**Issue by Shalomated** [VOLTTRON/volttron#2689]
Hello, please I am new to volttron. After installing and activating using "source env/bin/activate", I tried starting volttron using ./start-volttron, but get the feed back below

![image](https://user-images.githubusercontent.com/85184890/120357744-62ff9a00-c2cb-11eb-864d-a1431bb98964.png)

On checking the volttron.log file, this is the output

![image](https://user-images.githubusercontent.com/85184890/120358066-bb369c00-c2cb-11eb-935d-509b697e37a7.png)

Please help

**Comment by craig8** [comment]
Based upon what I see it means there are more than one volttrons running.

Please execute:

ps aux |grep volttron

If there are volttrons there then

killall -9 volttron


That should fix the issue....

From: Shalomated ***@***.***>
Sent: Tuesday, June 1, 2021 9:24 AM
To: VOLTTRON/volttron ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VOLTTRON/volttron] Volttron Not Starting (#2689)

Check twice before you click! This email originated from outside PNNL.


Hello, please I am new to volttron. After installing and activating using "source env/bin/activate", I tried starting volttron using ./start-volttron, but get the feed back below

[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F85184890%2F120357744-62ff9a00-c2cb-11eb-864d-a1431bb98964.png&data=04%7C01%7CCraig.Allwardt%40pnnl.gov%7Cfad9085b8fc64e8bffa708d92519ac54%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C637581614537231627%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UQtrE3m%2BTIiJBFpyhSGOrUBNkcPb%2F8GfeDspyAIfJYE%3D&reserved=0>

On checking the volttron.log file, this is the output

[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F85184890%2F120358066-bb369c00-c2cb-11eb-935d-509b697e37a7.png&data=04%7C01%7CCraig.Allwardt%40pnnl.gov%7Cfad9085b8fc64e8bffa708d92519ac54%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C637581614538057993%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NLL3aU8i7VPrEF4LCj%2FznP%2FyrWMFtPBLE8a0YdepqhY%3D&reserved=0>

Please help

-

**Comment by craig8** [comment]
@VOLTTRON/main-developers  we should see about making this a bit more robust when there is a bind error.  The only issue I am not sure about is if the arguments to start the agent aren't the same then what do we do?

**Comment by Shalomated** [comment]
> Based upon what I see it means there are more than one volttrons running. Please execute: ps aux |grep volttron If there are volttrons there then killall -9 volttron That should fix the issue.... From: Shalomated ***@***.***> Sent: Tuesday, June 1, 2021 9:24 AM To: VOLTTRON/volttron ***@***.***> Cc: Subscribed ***@***.***> Subject: [VOLTTRON/volttron] Volttron Not Starting (#2689) Check twice before you click! This email originated from outside PNNL. Hello, please I am new to volttron. After installing and activating using "source env/bin/activate", I tried starting volttron using ./start-volttron, but get the feed back below [image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F85184890%2F120357744-62ff9a00-c2cb-11eb-864d-a1431bb98964.png&data=04%7C01%7CCraig.Allwardt%40pnnl.gov%7Cfad9085b8fc64e8bffa708d92519ac54%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C637581614537231627%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UQtrE3m%2BTIiJBFpyhSGOrUBNkcPb%2F8GfeDspyAIfJYE%3D&reserved=0> On checking the volttron.log file, this is the output [image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F85184890%2F120358066-bb369c00-c2cb-11eb-935d-509b697e37a7.png&data=04%7C01%7CCraig.Allwardt%40pnnl.gov%7Cfad9085b8fc64e8bffa708d92519ac54%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C637581614538057993%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NLL3aU8i7VPrEF4LCj%2FznP%2FyrWMFtPBLE8a0YdepqhY%3D&reserved=0> Please help - You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVOLTTRON%2Fvolttron%2Fissues%2F2689&data=04%7C01%7CCraig.Allwardt%40pnnl.gov%7Cfad9085b8fc64e8bffa708d92519ac54%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C637581614538067955%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BBuTYJZ2fdpEhS6vA%2BYWqZIOv9epAlwEbjCjd%2B3T3Zg%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA6LON4KRJ6FGCIZAIO4XKTTQUCQZANCNFSM455AJCIQ&data=04%7C01%7CCraig.Allwardt%40pnnl.gov%7Cfad9085b8fc64e8bffa708d92519ac54%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C637581614538067955%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PsjLho2r38ArRmXg1jj%2FfG4qYZkw1FfA%2BrhDor93z7s%3D&reserved=0>.

Dear Craig, thanks for the response. After trying out the command you suggested, this is the feedback I got

![image](https://user-images.githubusercontent.com/85184890/120373248-bbd82e00-c2dd-11eb-849a-6f9b04671e6d.png)

I am not sure, but from what I suspect, there are no volttrons as I newly installed volttron on this device

**Comment by craig8** [comment]
killall -9 volttron

killall is one word.

**Comment by Shalomated** [comment]
It worked!

Thanks a lot Craig
