### ISSUE TITLE
Cant locate the Master Driver Agent

### ISSUE THREAD

**Issue by nitin-barthwal** [VOLTTRON/volttron#2701]
NOTE issues are for bugs/feature requests not support.  Please ask at https://stackoverflow.com/questions/tagged/volttron for help

### Description of Issue
I was following an office Hours (Office Hours - June 8, 2018) where presenter installed Master Driver Agent which was lying in service/core directory.
But I am unable to locate this directory.
 Is it moved to some other location or became obsolete?
 
### Screenshots

![image](https://user-images.githubusercontent.com/44734793/122252198-1323f400-cec3-11eb-8394-eef9a597b70c.png)

### Steps to Reproduce
$python scripts/install-agent.py -s services/core/MasterDriverAgent

**Comment by craig8** [comment]
The masterdriver has been renamed to PlatformDriver.  Please use that name instead.
