### ISSUE TITLE
Documentation that goes with the versions

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#279]
Currently we use the wiki for documentation.  The problem with that is the wiki doesn't allow for versioning to go along with the specific version of the code.  There is no way to easily keep straight what part of the wiki goes with which item.

I want to move our documentation out of our wiki and into a root level docs folder.  This will allow us to keep different versions depending on what branch is currently being looked at.  It also will allow us to use a service such as readthedocs to host each of the different versions of our documentation.  This can be done automatically as part of the travis ci build 

There will be a couple issues I assume.  I am making the assumption that we move to readthedocs.org with our documentation.

 1. There is alot of documentation to sift through currently (not a problem, just a pain).
 1. There is better support for rst format than there is for md.
 1. We need to be more diligent in our documentation and I think this will help us have a place to "verify" each others documentation.

@jhaack

**Comment by jhaack** [comment]
Being able to update documentation on a new/revised feature without breaking the documentation for an existing/old feature would certainly make life easier for everyone.
