### ISSUE TITLE
remove duplicate mention of pyzmq and wheel in requirements.py and bootstrap.py

### ISSUE THREAD

**Issue by schandrika** [VOLTTRON/volttron#2796]
pyzmq is mentioned twice in bootstrap.py leading possible confusion when manually pinning version and testing.
options_requirements gets installed before others - so include wheel in this instead of adding this explicitly in bootstrap.py. This way all packages and versions are listed in one file

**Comment by shwethanidd** [comment]
pyzmq is pinned to 22.2.1 for VOLTTRON 8.x and 19.0.1 for VOLTTRON 7.x.
