### ISSUE TITLE
Synchronize VOLTTRON readme and readthedocs

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#2889]
### Description of Issue

There exist inconsistencies between the main documentation in readthedocs and the readme on github.

Readthedoc main page and readme of github should contain almost all of the same content.  Exceptions are:

  - readthedocs should have a link to a secondary page for rabbitmq installation
  - README should reference the readthedocs secondary page for the main site.
 
Updates to the contents:

 - How to set up the VOLTTRON_HOME variable
 - Show how to tell the agent status ```vctl status```

**Comment by kefeimo** [comment]
Transfer Readme task to Update README #2923
