### ISSUE TITLE
Improve Base Historian Performance

### ISSUE THREAD

**Issue by kmonson** [VOLTTRON/volttron#291]
On low power devices the base historian has trouble keeping up with a large volume of messages. 

We need to improve how we use sqlite or replace it with something else.

**Comment by kmonson** [comment]
Still other improvements to be made. There is an index on the cached history table that is probably unneeded.

**Comment by kmonson** [comment]
Could also experiment with increasing page sizes.

**Comment by craig8** [comment]
@kmonson update or close if we are good with our current.

**Comment by kmonson** [comment]
We still need to look at this.

**Comment by kmonson** [comment]
I looked into removing an index that is not technically required but does add some safety thinking that it would help with performance. It did not. As that is the case we can safely assume that changing page counts in sqlite will not be beneficial as well.
