### ISSUE TITLE
Modbus and BACnet support over RS-485

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#301]

**Comment by craig8** [comment]
Thoughts?  Look into our EVSE work for thoughts perhaps?  Is this doable and do we want to do it now. or future?

**Comment by kmonson** [comment]
BACnet and Modbus over serial are a very different animal that firing up pyserial and giving it a go (which is what out EVSE stuff basically does). 

BACnet is a complex protocol and very sensitive to timing issues. This would require rewriting the bacnet proxy (or writing a separate special one) from scratch. It would be probably a months worth of work (or more). Also, in a non-realtime OS (such as Linux) BACnet over serial is fraught with peril. I can't say for certain it would work.

**Comment by jhaack** [comment]
Closing until community need
