### ISSUE TITLE
market isn't working correctly 

### ISSUE THREAD

**Issue by AntonLED** [VOLTTRON/volttron#3066]
I'm trying to setup market in my VOLTTRON system. 

For this I use **market_serviceagent-1.0** in _/volttron/services/contrib/MarketServiceAgent_ 
and some example market-agents:
- **meteragent-0.1**
- **electric_buyeragent-0.1**
- **electric_meteragent-0.1**
from _/volttron/examples/MarketAgents._

I don't see any response. 
The main reason, I think, is that the market-service doesn't call the callback functions from market participants code (for example, like on a screenshot)
![image](https://user-images.githubusercontent.com/57152042/213716086-1f0e8325-a680-4a57-8998-b9ef04543224.png)

Operating System: 
 - ubuntu 22.04 LTS
 - Volttron Version 8.2

**_P.S._**
in the future, I want to set up a market for single board computers (arm architecture), for example Raspberry Pi

**Comment by AntonLED** [comment]
I solved this problem by changing market service-agent type from event_driven to periodic:
![image](https://user-images.githubusercontent.com/57152042/213788381-b6c5648d-ae3c-4659-b897-61820a943caa.png)

**Comment by awoz** [comment]
Is there a pull request for this fix? Otherwise consider re-opening this issue so that dev team can submit your corrections and test for potential regressions.

**Comment by craig8** [comment]
@rlutes have we done anything with the event_driven in a while?  Might be worth looking at.
