### ISSUE TITLE
Historians and 2.0 agents

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#310]
There should be some tests wrapped around the 2.0 agent publishes to the bus.  Also there should be a way to tell that a message is from a 2.0 agent other than in the sender.

Perhaps an AgentVersion header that could be placed in the header and then that can be forwarded on.

**Comment by schandrika** [comment]
@craig8  Added min_compatible_version and max_compatible_version information to publish header information instead of single AgentVersion variable.
