### ISSUE TITLE
periodic timers

### ISSUE THREAD

**Issue by carlatpnl** [VOLTTRON/volttron#315]
would be useful aid to debugging to be able disable timers be setting their time to 0 so they are not called at all, but this does not seem to be permitted.

Also, it appears that each timer is called once initially at startup, then the timer begins, it would be good to have an option to disable the initial call.

**Comment by craig8** [comment]
One can uses code to start and stop periodic timers via rpc methods.

**Comment by carlatpnl** [comment]
an example of how to do such would have been appreciated.
