### ISSUE TITLE
Create Matlab interfaces for Volttron

### ISSUE THREAD

**Issue by poorva1209** [VOLTTRON/volttron#319]
- [x] Convert 2.0 driven agent model to 3.0 version
- [x] Create generic agent for matlab applications
- [x] Create Matlab Proxy to use Matlab Python engine
- [x] Test Matlab interface with CCSI simulations/application
- [x] Create integration test with volttron testing platform

**Comment by cyrus19901** [comment]
Hi Poorva,

I am working on integrating Matlab and volttron and taking inputs form matlab and hence controlling volttron using an algorithm based on the inputs .

Can you give some more insight on this.

Thanks,
Rajveer
