### ISSUE TITLE
Phone home for remote configuration

### ISSUE THREAD

**Issue by utalk2** [VOLTTRON/volttron#331]
Need to have ability for the VOLTTRON instance to phone home to management console in order to know when the device has failed or lost connection.

**Comment by craig8** [comment]
These are two distinct things.  The title is coming, the comment is handled by "status" which is currently displayed in the VMC.

**Comment by schandrika** [comment]
Is this related to alert and email agent?

**Comment by shwethanidd** [comment]
Alerts and emailer agent handles this issue
