### ISSUE TITLE
actuator should not access array agent id to schedule new task

### ISSUE THREAD

**Issue by schandrika** [VOLTTRON/volttron#333]
Actuator should fail to schedule a task when the agent id is an array as it cannot be used as key in dictionary. If no error is thrown during the request_schedule process, the next schedule request with a conflict will fail with "unhashable type: list " error instead of CONFLICTS_WITH_EXISTING_SCHEDULES. 
Please see test method  test_schedule_error_intarray_agentid  in test_actuator_pubsub.py and test_actuator_rpc.py.  Please remove the decorator pytest.mark.xfail to test

**Comment by craig8** [comment]
@kmonson please provide status and such

**Comment by kmonson** [comment]
OBE Agent ID arg is now ignored.
