### ISSUE TITLE
Actuator does not throw MISSING_AGENT_ID when a get is done without a agent id

### ISSUE THREAD

**Issue by schandrika** [VOLTTRON/volttron#334]
Actuator does not throw MISSING_AGENT_ID when a get is done without a agent id in the header. i.e. with
header = {
        'requesterID': None
    }
or 
header = {
        }

Get is successful. Is this expected behavior? If so we should update the documentation.  Refer to test method test_get_error_none_agent and test_get_error_empty_header in test_actuator_pubsub.py. Please remove the decorator pytest.mark.xfail to test

**Comment by schandrika** [comment]
Agent id is not necessary for get any more. Updated wiki. Yet to update user guide

**Comment by schandrika** [comment]
@kmonson  could you please update user guide for this

**Comment by kmonson** [comment]
The new docs on readthedocs are correct.
