### ISSUE TITLE
Device driver failure when MasterDriver is started too soon after proxy.

### ISSUE THREAD

**Issue by rlutes** [VOLTTRON/volttron#350]
If a device driver is started immediately after the BACnetProxy (say sequentially on one volttron-ctl start command) then device drivers may fail to hookup correctly and launch.

**Comment by kmonson** [comment]
Bacnet interfaces need to be able to handle the proxy not running. Right now they just die.

**Comment by kmonson** [comment]
Fixed in 6d6727338b586d9d176c6798c98f1a00c706b17e
