### ISSUE TITLE
Utilize groups and roles in authentication file

### ISSUE THREAD

**Issue by zbeech** [VOLTTRON/volttron#353]
The authentication file (auth.json) accepts _capabilities_, _roles_, and _groups_ fields. The _roles_ and _groups_ fields are not currently utilized.

_Roles_: set of capabilities
_Groups_: set of roles

This should be user definable in auth.json.

**Comment by poorva1209** [comment]
If we are using groups and roles now, this should be updated in auth documentation walkthrough.

**Comment by zbeech** [comment]
@poorva1209 You're right. I missed that when I read the walk through.

**Comment by zbeech** [comment]
@poorva1209 Although groups and roles are supported in the backend, we don't have a good interface to edit these. I will update the documentation once #893 is resolved.
