### ISSUE TITLE
sMAP historian agent should remove "/backend" from urls used to communicate with server.

### ISSUE THREAD

**Issue by kmonson** [VOLTTRON/volttron#357]
The urls that the sMAP historian agent seem to be incorrect. 

Testing on Intellimation's sMAP indicates that we should remove "/backend" from all urls or at least give the user more control of urls used during setup.

**Comment by jhaack** [comment]
Some versions of sMAP use backend and others don't. As long as it's configurable that should be fine.

**Comment by craig8** [comment]
No longer supporting sMAP hjistorian.
