### ISSUE TITLE
Restrict interactions with platforms in developer mode

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#359]
Platforms running in developer (unsecured) mode should not be allowed to interact with secured platforms.

**Comment by craig8** [comment]
if the secured platform contacts the unsecured platform the response will be a None for the serverkey.  That is how the secured platform can tell that it is in developer mode.  This should be remembered as we finish up #320 #250

**Comment by craig8** [comment]
Connection will timeout if either end doesn't have the same state.
