### ISSUE TITLE
Implement an sMAP historian

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#36]
Implement an sMAP based new historian for backward compatibility.

**Comment by craig8** [comment]
Is the present smap driver with twisted the 2.0 version?

**Comment by craig8** [comment]
Just rolling any issues that are referencing sMAP.

#12 #7 #5

**Comment by jhaack** [comment]
Initial Writing Historian done.
Next the Querying half.

**Comment by jhaack** [comment]
Using the POST interface to query private streams seems to have issues. To get around this, use the data, prev, or next url based lookup.

For instance /backend/api/data/uuid/<uuid>?key=<key>&starttime=1429224582000&endtime=1429225602000&limit=1000

/prev and /next work similarly and give you limit data points before or after the input time.

Can be found on: http://www.cs.berkeley.edu/~stevedh/smap2/archiver.html

**Comment by craig8** [comment]
Closing this item with the above note on private stream using alterative api
