### ISSUE TITLE
Bootstrap fails to build gevent for Python 2.7.6.

### ISSUE THREAD

**Issue by rlutes** [VOLTTRON/volttron#365]
Bootstrap process will fail to build wheel for gevent.  This occurs for gevent > 1.0.1 and Python version 2.7.6.  Work around is to install older version of gevent or newer Python interpreter.

**Comment by craig8** [comment]
I am not sure what to do with this as this is my history and everything worked out with a minimal server just like you mentioned.

See the following image.

![image](https://cloud.githubusercontent.com/assets/3979063/13308103/6c28f5f6-db25-11e5-8f7e-7f48ebe5559d.png)


In addition http://volttron.readthedocs.org/en/develop/ is the instructions that I used which are the same that is in the quickstart of the wiki.

Was yours on a board or on a desktop system?  VM or Not?

**Comment by rlutes** [comment]
64 bit minimal install and non-server.

**Comment by craig8** [comment]
Ok I will try that now.

**Comment by rlutes** [comment]
Could not replicate issue on another system running the same Ubuntu version and Python interpreter.
