### ISSUE TITLE
Be able to specify the table names in the SQLHistorian

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#366]
In the configuration file be able to specify the following for the sqlhistorian.  I think this would be good not to be in the connection params but under a seperate key.

something like

````
"defs": {
    "table_prefix": "", 
    "data_table_name": "data",
    "topic_table_name": "topics",
   ....
}

**Comment by schandrika** [comment]
@craig8 -  I have pushed fix to feature/historian.
