### ISSUE TITLE
Add volttron-ctl tests for authorization commands

### ISSUE THREAD

**Issue by zbeech** [VOLTTRON/volttron#383]
commands to test:
- auth-list
- auth-add
- auth-remove
- auth-update

**Comment by craig8** [comment]
So based upon your march 10 commit is this done?  I am going to push to 3.5.1 if not.

**Comment by zbeech** [comment]
This isn't complete. I added tests for the AuthFile API, but I also would like to add tests that actually run the volttron-ctl commands (e.g, `volttron-ctl auth-add`, `volttron-ctl auth-update`).
