### ISSUE TITLE
Posting to sMAP historian

### ISSUE THREAD

**Issue by BalazsHoranyi** [VOLTTRON/volttron#389]
I am running a sMAP historian locally on port 8000 and trying to publish data to it. However the way the smaphistorian is trying to publish data is though http://<ip>:8000/backend/add/key. However that method is not allowed. To add data I need to be able to post to http://<ip>:8079/add/key. Is there a way to specify the url? Thanks

**Comment by jhaack** [comment]
Duplicates #357
