### ISSUE TITLE
Build containers for each installed agent

### ISSUE THREAD

**Issue by zbeech** [VOLTTRON/volttron#393]
In order to set permissions/capabilities for individual agents we need to isolate agents from each other. In particular, we need to prevent agents from reading other agents secret keys. We can accomplish this with containers and/or Linux namespaces.

**Comment by shwethanidd** [comment]
@schandrika can you check if this is covered with secure agents work. Not the containers part, but limiting access to secret keys

**Comment by craig8** [comment]
Handled in #2202
