### ISSUE TITLE
Base services should automatically use the heartbeat

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#394]
As a follow on to #390 the following service agents should use the heartbeat functionality.

- ControlService
- PubSubService
- MasterWebService
- CompatPubSub

And agents that should by default use this when installed via normal config file
- MasterDriver
- ProxyAgents
- Historians
- VolttronCentral
- Platform

**Comment by mikeroup** [comment]
CompatPubSub does not inherit from Agent

**Comment by mikeroup** [comment]
What is MasterWebService?

**Comment by craig8** [comment]
It's available in the feature/web branch.  Don't worry about that one I will use your pattern for dealing with that one.
