### ISSUE TITLE
Have WeatherAgent publish data on startup

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#395]
The WeatherAgent has a long poll time and so it's not obvious it is working when it first starts up. By doing an initial publish it would be obvious everything is working.

**Comment by craig8** [comment]
@jhaack I know we have an update to this agent that was created.   I don't think that this update addresses this, nor do I know if this is still an issue.

**Comment by shwethanidd** [comment]
@jklarson can you comment

**Comment by jklarson** [comment]
I suspect this is overcome by events as there is now a base weather service and multiple implemented service agents. I can check it out in the near future.

**Comment by jhaack** [comment]
The issue with this was that it was hard to tell if the original weather agent was working if it had a long interval since you would have to wait that time period before getting your first publish. Does the new weather agent publish on startup? If so then this issue can be closed.

**Comment by jklarson** [comment]
The new service ages do publish on startup, this issue can be closed.
