### ISSUE TITLE
API to create ephemeral topics for direct agent to agent communication via message bus

### ISSUE THREAD

**Issue by fstshrk** [VOLTTRON/volttron#397]
On the same VOLTTRON platform, direct agent to agent communication can be supported via creation of an ephemeral topic that only the two agents are authorized to communicate through. 

We need an API to create these topics and manage the authorization file.

**Comment by craig8** [comment]
So rpc methods are not how we  want to do this.  That already exists.

**Comment by shwethanidd** [comment]
Covered as part of protected topics and agents can use protected base topic and subtopics
