### ISSUE TITLE
Implement a common subsystem.

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#402]
Core is not the place to put things such as health and heartbeat.  Instead let's create a subsystem called common that we can put such things that we want all agents to have, without cluttering up the core namespace.

#390

**Comment by mikeroup** [comment]
Why not put them in the base agent?

**Comment by craig8** [comment]
One reason is to separate it into the namespace so that it never will get stomped on by a user making their own enable-heartbeat function or whatever.

**Comment by craig8** [comment]
See back on #390

**Comment by craig8** [comment]
I think this is actually a not gonna fix it...and we just get rid of it.
