### ISSUE TITLE
Overwrite auth entries does not work as expected

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#409]
This may have been seen to in a branch

```
# Calling this twice with the same publickey produces a AuthFileEntryAlreadyExists even though the default for add is to overwrite the entry.

        authfile = AuthFile()
        authentry = AuthEntry(
            credentials="CURVE:{}".format(vcpublickey)
        )

        authfile.add(authentry)
```

**Comment by craig8** [comment]
@zbeech I went ahead and fixed this, but please look over the changes that I have made and make sure they make sense to you.

**Comment by zbeech** [comment]
@craig8 Your fixes look good to me. I added a few more auth-file tests and I found a couple more bugs. I fixed these in feature/auth-file-fix.
