### ISSUE TITLE
SQLHistorian fails to launch with sqlite backend

### ISSUE THREAD

**Issue by mikeroup** [VOLTTRON/volttron#428]
Issue present in master but not in develop. May be fixed in 3.5.

**Comment by jhaack** [comment]
Unable to replicate. Cloned master and was able to start up a sqlite based platform historian. What setup are you using where this fails?

**Comment by craig8** [comment]
The configure file in SQLHistorian directory.

Sent from my iPad

On Mar 30, 2016, at 7:00 AM, jhaack <notifications@github.com<mailto:notifications@github.com>> wrote:


Unable to replicate. Cloned master and was able to start up a sqlite based platform historian. What setup are you using where this fails?

**Comment by craig8** [comment]
Not an issue
