### ISSUE TITLE
BACPypes update breaks configuration grabber

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#429]
The latest version of BACPypes breaks the configuration grabber. Must revert to 0.13.2 to get it working again.

Either pin BACPypes version to this or adjust code to new version (if it's backward compatible)

**Comment by craig8** [comment]
I assume we must adjust this in the requirements file.

Sent from my iPad

On Mar 30, 2016, at 5:56 AM, jhaack <notifications@github.com<mailto:notifications@github.com>> wrote:


The latest version of BACPypes breaks the configuration grabber. Must revert to 0.13.2 to get it working again.

Either pin BACPypes version to this or adjust code to new version (if it's backward compatible)

**Comment by kmonson** [comment]
We've pinned this to 0.13.2 for now. Until I can come up with a reproducible case Joel won't be able to get it fixed.

**Comment by craig8** [comment]
from what @rlutes said pinning this to 0.13.2 has broken things that we are using on the campus demo

**Comment by craig8** [comment]
@kmonson see above comment.
