### ISSUE TITLE
Ability to add devices using VC UI

### ISSUE THREAD

**Issue by jchap-pnnl** [VOLTTRON/volttron#443]
Implement features in the Volttron Central web interface for adding devices. Steps include scanning for BACnet devices, configuring devices, and editing the registry configuration files.

**Comment by jchap-pnnl** [comment]
These are the mockups for the design that will be implemented:
![page_1](https://cloud.githubusercontent.com/assets/15679599/14214967/eb7e4234-f7f4-11e5-8f7d-fa050c9aba60.png)
![page_2](https://cloud.githubusercontent.com/assets/15679599/14214968/eb85bf8c-f7f4-11e5-81d9-b4b234412f81.png)
![page_3](https://cloud.githubusercontent.com/assets/15679599/14214962/eb67b6fe-f7f4-11e5-83e7-55cee0061943.png)
![page_4](https://cloud.githubusercontent.com/assets/15679599/14214964/eb6c42aa-f7f4-11e5-8518-7eb00dd9501b.png)
![page_5](https://cloud.githubusercontent.com/assets/15679599/14214963/eb6a042c-f7f4-11e5-8bc9-819f56c95e16.png)
![page_6](https://cloud.githubusercontent.com/assets/15679599/14214966/eb6caa60-f7f4-11e5-8f3a-cc41002682e8.png)
![page_7](https://cloud.githubusercontent.com/assets/15679599/14214961/eb671190-f7f4-11e5-8fa2-4f618535d9c9.png)
![page_8](https://cloud.githubusercontent.com/assets/15679599/14214965/eb6c4c3c-f7f4-11e5-8d10-efcaa4a6efb9.png)

**Comment by craig8** [comment]
We have merged into develop now woo hoo!
