### ISSUE TITLE
ILC Documenation

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#450]

**Comment by kmonson** [comment]
Is this done?

**Comment by craig8** [comment]
@rlutes @jhaack  we need to have volttron-applications.readthedocs.io as well.

**Comment by shwethanidd** [comment]
@rlutes any progress on this?

**Comment by shwethanidd** [comment]
Created new issue in https://github.com/VOLTTRON/volttron-applications/issues. Issue #77
