### ISSUE TITLE
Implement Pub/Sub subsystem over VIP

### ISSUE THREAD

**Issue by hashstat** [VOLTTRON/volttron#48]
The pub/sub sockets of version 2.x are being replaced by a single VIP socket and pub/sub will become a VIP subsystem. Three possible techniques for implementing pub/sub over VIP follow:

1. Implement the entirety of pub/sub as a set of RPC calls over the RPC subsystem (piggybacked).
2. Implement the entirety of pub/sub as its own protocol and subsystem (self-contained).
3. Create a subsystem for sending pub/sub messages and manage subscriptions over RPC (hybrid).

Option 3 seems to provide the most flexibility and will likely be the final solution.

**Comment by craig8** [comment]
This has been in use for a while now.  I am closing this as it is now in the new vipagent package as of e795d1ff1580efeba800b82a9729738edf9ad98d
