### ISSUE TITLE
Update VC's old chart area to use new chart features

### ISSUE THREAD

**Issue by jchap-pnnl** [VOLTTRON/volttron#513]

**Comment by jchap-pnnl** [comment]
Previous commit (5093af3) also included removing platform UUID from getting chart topics and added getting VC platform to checking for historian running. Using the platform UUID to figure out if it was the VC platform and then check its historian caused problems for when the vc platform wasn't registered (issue #592).

The handling of the platform UUID will have to be added back in if/when we get topics and add charts for remote platforms, too. Currently, all charts and topics -- even those for remote platforms -- are only reported to VOLTTRON Central through the VC platform.

**Comment by jhaack** [comment]
@jchap-pnnl Complete?

**Comment by jchap-pnnl** [comment]
Yes, it's complete.
