### ISSUE TITLE
Auth documenation clean up

### ISSUE THREAD

**Issue by zbeech** [VOLTTRON/volttron#526]
The Authentication and Authorization documentation needs to be cleaned up in readthedocs. The KeyStore class needs to be documented as well.

**Comment by craig8** [comment]
Please make sure to branch this off of the releases/3.5rc branch.  I will then merge it back into both the releases/3.5rc branch and into develop.

**Comment by zbeech** [comment]
We can open more specific issues related to Auth documentation as they come up.
