### ISSUE TITLE
Issue with saving charts

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#533]
I believe that this issue has to do with the saving/loading of charts to the store.  To reproduce

1. Create a dashboard chart
1. Add a couple other charts that are not on the dashboard
1. Log out
1. Log in
1. Click on an leaf in the tree

The following image is how mine showed after that even though I only had clicked on one thing the other two charts that I had (not including the one that was in the dashboard) shows up. 

![new-chart](https://cloud.githubusercontent.com/assets/3979063/15272146/c426e7c4-1a20-11e6-8ea1-d24c069355cf.png)

**Comment by jchap-pnnl** [comment]
The steps outlined above don't reproduce the bug anymore. The issue was posted before the synchronization between the tree and the charts was finished. I recommend removing this issue.

**Comment by craig8** [comment]
Yup couldn't reproduce
