### ISSUE TITLE
Drop support for PLAIN authentication

### ISSUE THREAD

**Issue by zbeech** [VOLTTRON/volttron#541]
According to http://rfc.zeromq.org/spec:27:

"PLAIN makes no attempt at security or confidentiality. It is intended for use on internal networks where security requirements are low."

Although we have support for PLAIN authentication in volttron/platform/vip/socket.py, it is not used by the rest of the platform. If we drop PLAIN authentication we will be left with NULL (no encryption or authentication) and CURVE (strong encryption and authentication). I don't see a good use case for the PLAIN mechanism.

**Comment by craig8** [comment]
I don't really think we actually are able to use PLAIN...even if we had it set up.

In addition...I believe we are going to be getting rid of --developer-mode shortly.  I would like to look into what it would take to use certs or gssapi as the method of entry however.

**Comment by shwethanidd** [comment]
We no longer use PLAIN authentication for zmq message bus.
