### ISSUE TITLE
Chart tooltips sometimes are hard to get rid of

### ISSUE THREAD

**Issue by jchap-pnnl** [VOLTTRON/volttron#545]
Sometimes a chart tooltip won't go away like it's supposed to if the mouse moves out of frame before the tooltip is told to hide. When this happens in combination with multiple charts and scrolling around on the page, you can't even tell which chart the tooltip belongs to so you can go back to that chart and re-hover over it and get the tooltip to go away.

**Comment by craig8** [comment]
BOO that sounds bad :(

**Comment by jchap-pnnl** [comment]
No worries, should be fixed now! Each chart now has an onoutsideclick detector that cleans up any lingering tooltips. That is, if any orphan tooltips are hanging around, just click the mouse and they go away.

**Comment by craig8** [comment]
very cool.
