### ISSUE TITLE
Enable aggregation of data points

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#565]
This will require changes to the drivers and historians:

- Drivers include new column which indicates how to aggregate this point (sum, avg, etc.)
- Future work: aggregation type would be automatic based on data model (Temps use avg)
- Create aggregator agents which store aggregated data for selected points. Agents can then query historian and specify aggregated data
- Aggregator agents are configured by:
  - Points to aggregate
  - How many missing data points to allow for missing points
  - time period (hourly, daily, etc)
 - Future work: aggregate historical data

**Comment by craig8** [comment]
So @schandrika it looks like not all of this is merged can you take a look at that?

**Comment by schandrika** [comment]
The first two points are not implemented but those are not in scope for the first phase of this implementation.

**Comment by jhaack** [comment]
#1001 #1002 Capture the points not implemented. Closing issues.
