### ISSUE TITLE
Creation of Routes for PubSub

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#584]
Draft design/scope of how messages will be routed from one endpoint to another.

The facility to allow this will be a pubsub call with the root of that the route/ topic.

**Comment by poorva1209** [comment]
Route method:
def route(self, requester_id, topics_values, **kwargs)

where topic_values is in the format
[('campus/building/device1/point1', value1), 
('campus/building/device2/point2', value2)]

**Comment by craig8** [comment]
Note this issue is going to be used with #604 to work properly.

**Comment by shwethanidd** [comment]
Covered by multi-platform connection and federation and shovel in rabbitmq feature
