### ISSUE TITLE
Need a scrollbar for the Platforms screen

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#616]
Platform tab has no scrollbar which is a problem if there are a large number of agents

**Comment by jchap-pnnl** [comment]
I'm not sure why you didn't see a scrollbar. It shows up here:

![image](https://cloud.githubusercontent.com/assets/15679599/15915142/a56bffca-2d9b-11e6-8295-ebd7c5b46bac.png)

**Comment by craig8** [comment]
I think @jhaack is talking about the actual platform screen.
![2016-06-09 21_57_02-volttron central beta](https://cloud.githubusercontent.com/assets/3979063/15954576/43bb1f7a-2e8d-11e6-8130-aed8d3702c7a.png)
