### ISSUE TITLE
VolttronCentralAgent should be able to request to manage a PlatformAgent

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#63]
Currently a PlatformAgent calls out to the VolttronCentral agent and establishses a connection.  This will allow a PlatformAgent to be dynamically joined to the VolttronCentral agents sphere of influence.

**Comment by jhaack** [comment]
If the VOLTTRON platform is hardcoded to a VOLTTRON Central it should attempt to connect to that VC and refuse requests for management from other VCs.
If the VOLTTRON platform is not hardcoded to a VC, it will respond to the first management request from a VC. THereafter, it will refuse further management requests from other VCs.
A VC may un-register a VOLTTRON platform (non-hardcoded). The VOLTTRON platform is then available for management requests from other VCs.

**Comment by fstshrk** [comment]
Can a VC also issue a command to cause a VOLTTRON platform to register to
another VC.

**Comment by craig8** [comment]
Sure that's not a problem since they are two different agents on two different vip networks.
