### ISSUE TITLE
Error installing agent through VOLTTRON Central

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#633]
agent_uuid = self._aip.install_agent(path)
  File "/home/volttron/volttron/volttron/platform/aip.py", line 296, in install_agent
    unpack(agent_wheel, dest=agent_path)
  File "/usr/local/lib/python2.7/dist-packages/wheel/tool/__init__.py", line 137, in unpack
    sys.stderr.write("Unpacking to: %s\n" % (destination))
IOError: [Errno 5] Input/output error

Restarting VOLTTRON solves the problem.

I have only seen this on one machine so it may be a problem specific to the board. Trying to replicate elsewhere.

**Comment by jhaack** [comment]
Verify this is solved by sending VOLTTRON output to dev/null

**Comment by craig8** [comment]
Verified this is fixed.
