### ISSUE TITLE
Constant retries when wrong server key is used in VIP call

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#638]
If an agent on platformA attempts to contact platformB with the wrong server key there is the potential for constant retries with the following error showing up on platformB:

CURVE I: cannot open client HELLO -- wrong server key?

https://github.com/zeromq/libzmq/blob/master/src/curve_server.cpp

This needs to be caught and prevented from constantly retrying.

**Comment by jhaack** [comment]
This may be a zmq version difference. Current behavior is the agent dies due to a zmq assertion failure.

**Comment by jhaack** [comment]
Still an issue, should be documented

**Comment by zbeech** [comment]
See http://stackoverflow.com/questions/38534520/how-can-i-debug-a-connection-issue-within-volttron/38596085#38596085 for background on this issue.

**Comment by zbeech** [comment]
I think this is out of our control short of modifying ZMQ.

**Comment by craig8** [comment]
Seems like this is something that is not going to be able to be fixed by us :( the >dev/null however will make it not as viewable.
