### ISSUE TITLE
MasterWebService adds 'allow-all' authentication entry

### ISSUE THREAD

**Issue by zbeech** [VOLTTRON/volttron#673]

**Comment by craig8** [comment]
ahh yeah.  relic from where we were doing this.

**Comment by jhaack** [comment]
@craig8  @zbeech  Still an issue?

**Comment by zbeech** [comment]
It is technically still in the code: https://github.com/VOLTTRON/volttron/blob/develop/volttron/platform/web.py#L202

We can remove this, and it won't affect the behavior because the AuthFile will always have at least one entry (the platform itself). Thus, `if not entries` will always be false.

**Comment by zbeech** [comment]
merged into develop
