### ISSUE TITLE
Create a historian backed by a more robust DB

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#68]
Possibly Postgres.

**Comment by craig8** [comment]
Would an of the nosql solutions be acceptable?

**Comment by jhaack** [comment]
That might be another issue. This was targeted more at Postgres/MySQL which are ones we've had people specifically ask about.

**Comment by fstshrk** [comment]
For time series data, a NoSQL solution may be acceptable. But a lot of the
queries we get have been about mysql/postgres.

**Comment by craig8** [comment]
For postgres
 - py-postgresql package is a python 3.0 version only. 
 - psycopg2 requires pg_config (I think this is only available when postgressql is installed.)
For mysql
 - Mysql-Python is available for python 2.7 and not for python 3.0
 - Requires that mysql server (not just client) is installed.

**Comment by craig8** [comment]
I will be using mysql as it is more comfortable for me.

**Comment by hashstat** [comment]
@craig8, please consider sticking to a DB package complying to the [Python DBAPI](https://www.python.org/dev/peps/pep-0249/) as much as possible. This should allow easily swapping out the underlying database with any other that also supports the API.

Also, are you targeting MySQL or it's forked, open-source sister, MariaDB?

**Comment by craig8** [comment]
Oh yes definitely using a DBAPI compliant driver

**Comment by craig8** [comment]
On second thought I will write a SQLHistorian that does this.
