### ISSUE TITLE
Agent isn't removed when removing running agent

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#71]
When an agent is runing (has a pid in status window) if the user removes the agent via volttron-ctl remove uuid...the agent still shows in the volttron-ctl status as being a running process.  

Trying to stop the agent at this point produces an error not found (i.e. volttron-ctl stop uuid).  volttron-ctrl clear does not remove the agent from volttron-ctl status list.

Restarting volttron does remove the agent from the volttron-ctl status list.

**Comment by loulupe** [comment]
I'm not sure if this is written somewhere, but just in case... to remove several agents with the same name (eg. listeneragent-3.0) we should write
$volttron-ctl remove --name -f listeneragent-3.0
