### ISSUE TITLE
Error in VC javascript in Internet Explorer 11

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#728]
I logged in and clicked to expand the registered instance.  The following image is the result in the console.  Note this is using develop, however it has the same front-end code as develop.

![volttron central beta - internet explorer_2016-09-01_20-15-19](https://cloud.githubusercontent.com/assets/3979063/18191605/34910d44-7081-11e6-9b75-76e5ae3934f9.png)

**Comment by jhaack** [comment]
Still an issue, @jchap-pnnl

**Comment by jchap-pnnl** [comment]
This appears to be an issue with IE not allowing anonymous functions. There are a lot of anonymous functions throughout VC. We can fix the issue by making them named functions. But are we supporting IE?

**Comment by craig8** [comment]
We have decided this is not something we are going to fix...
