### ISSUE TITLE
Add an Analysis node to the VC tree

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#731]
For analysis that is done at the leaf level (i.e. at the same node as the collector) have that data be displayed in the tree as well.

**Comment by jhaack** [comment]
Analysis prefix is currently removed by the base_historian making it hard to tell that it was an analysis topic.

These topics will be in the db but not a device.

**Comment by shwethanidd** [comment]
@jhaack is this a valid issue now?

**Comment by jhaack** [comment]
Close for now and wait for someone in the community to need it.
