### ISSUE TITLE
Logging does not seem to work in control.py

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#757]
The new logging that you put in on #756 does not show up when running the platform in -vv.   However I know the method is getting executed correctly because of a handy print statement.

**Comment by mikeroup** [comment]
Good catch. That is pretty weird. control.py has the control agent and the code for the command line tool so that could be a factor.

**Comment by mikeroup** [comment]
volttron-ctl has its own logging level. Try volttron-ctl -vv install

**Comment by craig8** [comment]
So this isn't an issue more than it's logging to a different pipe...i.e. we aren't going to get this data into say volttron.log

**Comment by mikeroup** [comment]
Correct. There might be a way to attach it to the volttron logger but I would defer to Kyle about that.

**Comment by craig8** [comment]
After discussing I believe that this is not an issue and will not be "fixed".   As @mikeroup reports -vv on the volttron-ctl does indeed give the output that I was thinking should go in the log.  And after conversations with the team I believe that is the behavior that should stay.
