### ISSUE TITLE
Documentation items for 4.0.1 and beyond!

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#762]
**New Documentation Needed**
- [ ] How to use the new applications repository in a VOLTTRON deployment
- [ ] How to write integration tests for your agent
- [x] Libraries needed for pytests (pip install pytest mock pytest-timeout)
- [ ] Document ActuatorAgent timezone issue
- [ ] Add section for using Pycharm rather than eclipse.  This should be a short task ;)
- [x] Add documentation on how to use the extended installations.  See volttron-ctl --help and look for the section 'Extra packaging options:'.  

**Updates Needed**
- [x] Management Demo
- [x] core_services/drivers/failover
- [X]  Update support information
- [X]  Include Python and Linux references

**Misc Issues**
- [x] there are two copies of VOLTTRON-version history
  - http://volttron.readthedocs.io/en/develop/overview/VOLTTRON-Versions.html
  - http://volttron.readthedocs.io/en/develop/roadmap/VOLTTRON_Versions.html
- [X]  Documentation style guide

**Comment by schandrika** [comment]
Created new issue for what is still incomplete. Closing this one.
