### ISSUE TITLE
Update failing tests

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#776]
Tests failing likely because they need to be updated
- [x] volttrontesting/testutils/test_platformwrapper.py::test_resinstall_agent[encrypted] FAILED
- [x] volttrontesting/testutils/test_platformwrapper.py::test_resinstall_agent[unencrypted] FAILED
- [x] volttrontesting/platform/packaging-tests.py::TestPackaging::test_can_create_package FAILED
- [x] volttrontesting/platform/packaging-tests.py::TestPackaging::test_can_extract_package FAILED
- [x] volttrontesting/platform/packaging-tests.py::TestPackaging::test_raises_error_if_agent_dir_not_exists FAILED

**Comment by schandrika** [comment]
Unable to reproduce first 2. For the remaining 3 created new test module. Did not delete the older one as I want to keep it around as reference whenever I update the new one for restricted code related tests
