### ISSUE TITLE
Config store error when using dynamic agent to connect to old platform

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#779]
Steps to replicate

1. Start up an instance using a pre-config store branch (3.5rc1 is a good canidate)
1. Start up an instance using a config store enabled branch (develop is good for this)
1. Create a dynamic agent from the config store enabled branch that attempts to connect to the pre-config store branch

**Comment by kmonson** [comment]
Fixed in 3de575545dd328565b52053f03b9fb4521d78a60
