### ISSUE TITLE
Uploading agent produces silent results

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#78]
The agent is uploaded fine (assuming it is a valid whl file), however there is not a good response from the webserver due to the streaming nature.  The stream is closed before the code has a chance to finish returning from the rpc call.

**Comment by craig8** [comment]
Install Agent must be finished off with this as well.

**Comment by jhaack** [comment]
@craig8  OBE?

**Comment by jhaack** [comment]
OBE
