### ISSUE TITLE
Need a mechanism for allowing local scripts to interact with the platform

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#782]
Original version of the driver update script fails because it has no entry in auth and no keypair to use for credentials.

This is going to be a common issue for scripts and we need a general and secure way to handle it.

**Comment by zbeech** [comment]
Is `./scripts/update_master_driver_config.py` the script of interest? Is this script intended to only be run on the same system as the platform? If so, then I think this `master_driver_update_agent` can use the platform's key pair.

**Comment by craig8** [comment]
As of #783 this is now in develop
