### ISSUE TITLE
web port when using a vcp isn't prompted for in volttron-cfg

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#798]

**Comment by mikeroup** [comment]
Could we stop asking for the port separately altogether?

**Comment by craig8** [comment]
Well not really...I think it's necessary on both our vip and http addresses.  In addition, we can obviously default to port 80 or 8080 on http...but we need both pieces or therre won't be a connection.  Either that or require them to always have the :8080 or whatever on it.
