### ISSUE TITLE
Improve vc UI responsiveness with Immutable.js

### ISSUE THREAD

**Issue by jchap-pnnl** [VOLTTRON/volttron#803]
Where it makes sense to do so, check for changes between immutable objects in shouldComponentUpdate methods to limit multiple re-renderings.

**Comment by jhaack** [comment]
@jchap-pnnl  Status?

**Comment by jchap-pnnl** [comment]
This has been addressed in the device config branch. So, the status should stay in progress until that branch is ready to merge.
