### ISSUE TITLE
Messages sent through the channel subsystem are dropped if the socket is closed too early

### ISSUE THREAD

**Issue by hashstat** [VOLTTRON/volttron#83]
ZeroMQ buffers messages for sending at a later time in a different thread, however, state used to translate between local socket address and channel subsystem addresses is cleaned up immediately when the socket is either closed or garbage collected. Any messages in the queue sent after the state is cleaned up is dropped and not delivered. This provokes a race condition in the sending of data. The current solution is for peers to coordinate a socket close, but it would be nice if something more automatic could be done.

Perhaps delaying the removal of state until some later time would be most appropriate.

**Comment by craig8** [comment]
@hashstat status of this?

**Comment by jhaack** [comment]
@shwethanidd @craig8 

Installing agent issue fixed. Is this still a problem outside that?

**Comment by jhaack** [comment]
OBE
