### ISSUE TITLE
WeatherAgent does not work properly with country/city instead of zip_code

### ISSUE THREAD

**Issue by damienpicard** [VOLTTRON/volttron#831]
The code of weatherAgent is not correct to use it with country/city instead of zip_code.
The following lines of the file: https://github.com/VOLTTRON/volttron/blob/master/services/core/WeatherAgent/weather/weatheragent.py

```
    agent_id = get_config('agentid')
    poll_time = get_config('poll_time')
    zip_code = get_config("zip")
    key = get_config('key')
    on_request_only = get_config('on_request_only')

    state = ''
    country = ''
    city = ''
    region = state if state != "" else country
    city = city
```

should be replaced by:

```
agent_id = get_config('agentid')
    poll_time = get_config('poll_time')
    zip_code = get_config("zip")
    state = get_config("state")
    country = get_config("country")
    city = get_config("city")
    key = get_config('key')
    on_request_only = get_config('on_request_only')
```

and also:

```
elif self.region != ""
```

by

```
elif region !=""
```

**Comment by damienpicard** [comment]
After adapting the code, the agent runs smoothly.

**Comment by craig8** [comment]
Great @damienpicard.  If it wouldn't be too much trouble could you see if the develop branch gives you the same issue.  It is what will be in master next week sometime.  Master is the most stable oldest branch.  See http://volttron.readthedocs.io/en/develop/roadmap/index.html for the roadmap.  Currently master is 3.0 code.

**Comment by damienpicard** [comment]
@craig8 the same issue remained in the develop branch. I issued a pull request fixing it.

**Comment by acedrew** [comment]
Is this resolved? There seems to be a lot of noise in the issues, love to get them pruned down a bit to current problems
