### ISSUE TITLE
Conflicting identity errors if issuing volttron-ctl commands too quickly

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#837]
Using terminator, issue a volttron-ctl command at the same time in multiple consoles. You will get one response and the rest will error with "conflicting identity".

Modify control.py to not use the set control identity (thus creating a random one) and you will get a response in all consoles.

Something to be aware of.

**Comment by schandrika** [comment]
This is documentated at https://volttron.readthedocs.io/en/develop/core_services/control/PlatformCommands.html
Control needs to use a known identity to work with auth capabilities
