### ISSUE TITLE
what is tcp in VIP address?

### ISSUE THREAD

**Issue by jun343** [VOLTTRON/volttron#861]
i want to make platform in volttron
but VIP address is error that is tcp has 6 address
so i found that however i can`t find tcp.

plz, how to find the tcp?

**Comment by jhaack** [comment]
tcp is the ip address of the machine VOLTTRON is deployed on. The tcp: prefix indicates that you'll be using an IP address instead of an ipc address.

**Comment by craig8** [comment]
tcp stands for transmission control protocol whilest ipc stands for interprocess communication.  ipc is used when multiple VOLTTRON instances are deployed on a single server and to communicate between the VOLTTRON process and other agent processes.

to find your tcp address you can use 

````
# The new way
ip addr

# The old way
ifconfig
````

Your output will have a 10.0.5.10 format.
