### ISSUE TITLE
possible typo in building Listener Agent

### ISSUE THREAD

**Issue by nikithark** [VOLTTRON/volttron#878]
[http://volttron.readthedocs.io/en/develop/devguides/setup/Building-VOLTTRON.html](url)

listeneragent-3.2 and not 3.0: four instances

**Comment by craig8** [comment]
Great @nikithark Would you like to take a stab at fixing those and submitting a pull request?  That would help us greatly!

The page you mentioned is available for edit here: https://github.com/VOLTTRON/volttron/blob/develop/docs/source/devguides/setup/Building-VOLTTRON.rst

**Comment by schandrika** [comment]
Documentation has been updated and reorganized
