### ISSUE TITLE
Add "volttron-ctl auth remove-known-hosts" command

### ISSUE THREAD

**Issue by zbeech** [VOLTTRON/volttron#908]
Users need a way to remove hosts from the known-hosts-file. This is especially important when a remote platform's public key changes.

**Comment by craig8** [comment]
when do you add an entry to the known-hosts file currently?

**Comment by zbeech** [comment]
Currently it is an entry can be added to the known-hosts file in two ways:

1. The `volttron-ctl auth add-known-host` command
2. In `main.py`, when the platform starts it adds its own public key so local agents automatically know what server key to use

**Comment by craig8** [comment]
And the purpose for 1 is ?  Will it overwrite the key in the known host file?  Is this for external agents connecting to the local platform?

**Comment by zbeech** [comment]
Yes, 1 is for agent (on platform A) connecting to external platform B. The user on platform A can run:

`volttron-ctl auth add-known-host --host $B_ADDR --server-key $B_PUB_KEY`

Then anytime agents on platform A need to connect to platform B they know what server key to use.

**Comment by craig8** [comment]
This seems like what I should be using in vcm and vc then.  Rather than adding both to auth.json. 

So there isn't a way to do it through an rpc method for vcp at present?

**Comment by zbeech** [comment]
Also, yes, the `add-known-hosts` will overwrite the the server key in the known-host file.

**Comment by zbeech** [comment]
No, there isn't currently an RPC method for this.

**Comment by zbeech** [comment]
merged into develop
