### ISSUE TITLE
Make compatiblity pub/sub service optional

### ISSUE THREAD

**Issue by hashstat** [VOLTTRON/volttron#92]
The 2.x compatibility shim is currently started as a default service. This should be an optional component, only started on platforms with 2.x device drivers and as a private service in 2.x agents.

**Comment by craig8** [comment]
Are we going to do this? @jhaack

**Comment by jhaack** [comment]
Let's do this for 5.0

**Comment by craig8** [comment]
I thought we were going to remove it completely?

**Comment by jhaack** [comment]
Remove for 6.0
