### ISSUE TITLE
Verify DataPublisher and provide usage documentation

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#921]
Verify DataPublisher works in 4.0 and provide documentation for proper usage.

**Comment by mikeroup** [comment]
The `replay.config` file doesn't seem to serve a purpose other than to say that the replay option is available. We could probably remove it.

We also have `oae_sample_data.csv` and `oae_sample_data_2.csv`. Do we need both of them?

**Comment by jhaack** [comment]
replay.config shows the options for configuring the publisher. This could be replaced with proper documentation in readthedocs.

Not sure what functional difference the two data sets have so go ahead and remove the second one.
