### ISSUE TITLE
MODBUS driver tries to get points that don't exist.

### ISSUE THREAD

**Issue by kmonson** [VOLTTRON/volttron#956]
The MODBUS driver tries to use the read range functionality of pymodbus everywhere it can. On some devices there are gaps in the registers. Those devices are terrible and should feel bad. (Just kidding!) If we try to read across one of those gaps it fails and the device fails to scrape.

We need to break up the range reads to skip any potential gaps.

**Comment by craig8** [comment]
@kmonson how difficult is this to deal with?

**Comment by kmonson** [comment]
Couple of days of work. I will have to rewrite how the driver chooses what ranges to scrape and create data structure to store those new smaller ranges.

**Comment by kmonson** [comment]
And testing.

**Comment by kmonson** [comment]
I think this is a few days of work, including testing.
