### ISSUE TITLE
UI Hangs when trying to open a platform in the tree

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#961]
Run through management demo.
Tree hangs when trying to open the tree for a platform running the master driver. Does not hang if platform has no master driver running.

Could be a problem with the UI or with the fakedriver

**Comment by craig8** [comment]
Is the platform the same platform as vc or the other one.

**Comment by craig8** [comment]
I am almost positive that this is because we don't have a forwardhistorian forwarding to the vc platform.  

I am going to install one now on the secondary platform and see if that does ideed fix the issue.

**Comment by craig8** [comment]
Hmmm I am wondering if this has to do with the no route to host for peer that I have seen in testing.  There seems to be a bit of that going around that I need to track down why.

**Comment by jchap-pnnl** [comment]
The problem is the client code gets into an infinite loop because the fake device's key is a single string "fake," but the code expects it to be a three-part path like "campus/building/device."
